-- political_division_state.sql
INSERT INTO public.political_division
  (id,
  description,
  name,
  fips,
  type
  )
VALUES
(nextval('public.hibernate_sequence'),'United States','US','US','FEDERAL'),
(nextval('public.hibernate_sequence'),'Alabama','AL','01','STATE'),
(nextval('public.hibernate_sequence'),'Alaska','AK','02','STATE'),
(nextval('public.hibernate_sequence'),'Arizona','AZ','04','STATE'),
(nextval('public.hibernate_sequence'),'Arkansas','AR','05','STATE'),
(nextval('public.hibernate_sequence'),'California','CA','06','STATE'),
(nextval('public.hibernate_sequence'),'Colorado','CO','08','STATE'),
(nextval('public.hibernate_sequence'),'Connecticut','CT','09','STATE'),
(nextval('public.hibernate_sequence'),'Delaware','DE','10','STATE'),
(nextval('public.hibernate_sequence'),'District of Columbia','DC','11','STATE'),
(nextval('public.hibernate_sequence'),'Florida','FL','12','STATE'),
(nextval('public.hibernate_sequence'),'Georgia','GA','13','STATE'),
(nextval('public.hibernate_sequence'),'Hawaii','HI','15','STATE'),
(nextval('public.hibernate_sequence'),'Idaho','ID','16','STATE'),
(nextval('public.hibernate_sequence'),'Illinois','IL','17','STATE'),
(nextval('public.hibernate_sequence'),'Indiana','IN','18','STATE'),
(nextval('public.hibernate_sequence'),'Iowa','IA','19','STATE'),
(nextval('public.hibernate_sequence'),'Kansas','KS','20','STATE'),
(nextval('public.hibernate_sequence'),'Kentucky','KY','21','STATE'),
(nextval('public.hibernate_sequence'),'Louisiana','LA','22','STATE'),
(nextval('public.hibernate_sequence'),'Maine','ME','23','STATE'),
(nextval('public.hibernate_sequence'),'Maryland','MD','24','STATE'),
(nextval('public.hibernate_sequence'),'Massachusetts','MA','25','STATE'),
(nextval('public.hibernate_sequence'),'Michigan','MI','26','STATE'),
(nextval('public.hibernate_sequence'),'Minnesota','MN','27','STATE'),
(nextval('public.hibernate_sequence'),'Mississippi','MS','28','STATE'),
(nextval('public.hibernate_sequence'),'Missouri','MO','29','STATE'),
(nextval('public.hibernate_sequence'),'Montana','MT','30','STATE'),
(nextval('public.hibernate_sequence'),'Nebraska','NE','31','STATE'),
(nextval('public.hibernate_sequence'),'Nevada','NV','32','STATE'),
(nextval('public.hibernate_sequence'),'New Hampshire','NH','33','STATE'),
(nextval('public.hibernate_sequence'),'New Jersey','NJ','34','STATE'),
(nextval('public.hibernate_sequence'),'New Mexico','NM','35','STATE'),
(nextval('public.hibernate_sequence'),'New York','NY','36','STATE'),
(nextval('public.hibernate_sequence'),'North Carolina','NC','37','STATE'),
(nextval('public.hibernate_sequence'),'North Dakota','ND','38','STATE'),
(nextval('public.hibernate_sequence'),'Ohio','OH','39','STATE'),
(nextval('public.hibernate_sequence'),'Oklahoma','OK','40','STATE'),
(nextval('public.hibernate_sequence'),'Oregon','OR','41','STATE'),
(nextval('public.hibernate_sequence'),'Pennsylvania','PA','42','STATE'),
(nextval('public.hibernate_sequence'),'Rhode Island','RI','44','STATE'),
(nextval('public.hibernate_sequence'),'South Carolina','SC','45','STATE'),
(nextval('public.hibernate_sequence'),'South Dakota','SD','46','STATE'),
(nextval('public.hibernate_sequence'),'Tennessee','TN','47','STATE'),
(nextval('public.hibernate_sequence'),'Texas','TX','48','STATE'),
(nextval('public.hibernate_sequence'),'Utah','UT','49','STATE'),
(nextval('public.hibernate_sequence'),'Vermont','VT','50','STATE'),
(nextval('public.hibernate_sequence'),'Virginia','VA','51','STATE'),
(nextval('public.hibernate_sequence'),'Washington','WA','53','STATE'),
(nextval('public.hibernate_sequence'),'West Virginia','WV','54','STATE'),
(nextval('public.hibernate_sequence'),'Wisconsin','WI','55','STATE'),
(nextval('public.hibernate_sequence'),'Wyoming','WY','56','STATE')
;