-- tax_definition state fuel
INSERT INTO public.tax_definition(id, tax_definition_key, description, tax_calc_strategy, tax_type, political_division_key, ordinal)
VALUES
(nextval('public.hibernate_sequence'), 'US_FEDERAL_FUEL','US Federal Fuel','fuelTaxCalculator','FUEL_FEDERAL', 'US', 6),
(nextval('public.hibernate_sequence'), 'AL_STATE_FUEL', 'AL State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '01', 6),
(nextval('public.hibernate_sequence'), 'AZ_STATE_FUEL', 'AZ State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '04', 6),
(nextval('public.hibernate_sequence'), 'AK_STATE_FUEL', 'AK State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '02', 6),
(nextval('public.hibernate_sequence'), 'AR_STATE_FUEL', 'AR State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '05', 6),
(nextval('public.hibernate_sequence'), 'CA_STATE_FUEL', 'CA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '06', 6),
(nextval('public.hibernate_sequence'), 'CO_STATE_FUEL', 'CO State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '08', 6),
(nextval('public.hibernate_sequence'), 'CT_STATE_FUEL', 'CT State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '09', 6),
(nextval('public.hibernate_sequence'), 'DE_STATE_FUEL', 'DE State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '10', 6),
(nextval('public.hibernate_sequence'), 'DC_STATE_FUEL', 'DC State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '11', 6),
(nextval('public.hibernate_sequence'), 'FL_STATE_FUEL', 'FL State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '12', 6),
(nextval('public.hibernate_sequence'), 'GA_STATE_FUEL', 'GA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '13', 6),
(nextval('public.hibernate_sequence'), 'HI_STATE_FUEL', 'HI State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '15', 6),
(nextval('public.hibernate_sequence'), 'ID_STATE_FUEL', 'ID State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '16', 6),
(nextval('public.hibernate_sequence'), 'IL_STATE_FUEL', 'IL State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '17', 6),
(nextval('public.hibernate_sequence'), 'IN_STATE_FUEL', 'IN State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '18', 6),
(nextval('public.hibernate_sequence'), 'IA_STATE_FUEL', 'IA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '19', 6),
(nextval('public.hibernate_sequence'), 'KS_STATE_FUEL', 'KS State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '20', 6),
(nextval('public.hibernate_sequence'), 'KY_STATE_FUEL', 'KY State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '21', 6),
(nextval('public.hibernate_sequence'), 'LA_STATE_FUEL', 'LA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '22', 6),
(nextval('public.hibernate_sequence'), 'ME_STATE_FUEL', 'ME State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '23', 6),
(nextval('public.hibernate_sequence'), 'MD_STATE_FUEL', 'MD State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '24', 6),
(nextval('public.hibernate_sequence'), 'MA_STATE_FUEL', 'MA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '25', 6),
(nextval('public.hibernate_sequence'), 'MI_STATE_FUEL', 'MI State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '26', 6),
(nextval('public.hibernate_sequence'), 'MN_STATE_FUEL', 'MN State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '27', 6),
(nextval('public.hibernate_sequence'), 'MS_STATE_FUEL', 'MS State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '28', 6),
(nextval('public.hibernate_sequence'), 'MO_STATE_FUEL', 'MO State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '29', 6),
(nextval('public.hibernate_sequence'), 'MT_STATE_FUEL', 'MT State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '30', 6),
(nextval('public.hibernate_sequence'), 'NE_STATE_FUEL', 'NE State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '31', 6),
(nextval('public.hibernate_sequence'), 'NV_STATE_FUEL', 'NV State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '32', 6),
(nextval('public.hibernate_sequence'), 'NH_STATE_FUEL', 'NH State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '33', 6),
(nextval('public.hibernate_sequence'), 'NJ_STATE_FUEL', 'NJ State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '34', 6),
(nextval('public.hibernate_sequence'), 'NM_STATE_FUEL', 'NM State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '35', 6),
(nextval('public.hibernate_sequence'), 'NY_STATE_FUEL', 'NY State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '36', 6),
(nextval('public.hibernate_sequence'), 'NC_STATE_FUEL', 'NC State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '37', 6),
(nextval('public.hibernate_sequence'), 'ND_STATE_FUEL', 'ND State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '38', 6),
(nextval('public.hibernate_sequence'), 'OH_STATE_FUEL', 'OH State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '39', 6),
(nextval('public.hibernate_sequence'), 'OK_STATE_FUEL', 'OK State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '40', 6),
(nextval('public.hibernate_sequence'), 'OR_STATE_FUEL', 'OR State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '41', 6),
(nextval('public.hibernate_sequence'), 'PA_STATE_FUEL', 'PA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '42', 6),
(nextval('public.hibernate_sequence'), 'RI_STATE_FUEL', 'RI State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '44', 6),
(nextval('public.hibernate_sequence'), 'SC_STATE_FUEL', 'SC State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '45', 6),
(nextval('public.hibernate_sequence'), 'SD_STATE_FUEL', 'SD State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '46', 6),
(nextval('public.hibernate_sequence'), 'TN_STATE_FUEL', 'TN State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '47', 6),
(nextval('public.hibernate_sequence'), 'TX_STATE_FUEL', 'TX State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '48', 6),
(nextval('public.hibernate_sequence'), 'UT_STATE_FUEL', 'UT State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '49', 6),
(nextval('public.hibernate_sequence'), 'VT_STATE_FUEL', 'VT State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '50', 6),
(nextval('public.hibernate_sequence'), 'VA_STATE_FUEL', 'VA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '51', 6),
(nextval('public.hibernate_sequence'), 'WA_STATE_FUEL', 'WA State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '53', 6),
(nextval('public.hibernate_sequence'), 'WV_STATE_FUEL', 'WV State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '54', 6),
(nextval('public.hibernate_sequence'), 'WI_STATE_FUEL', 'WI State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '55', 6),
(nextval('public.hibernate_sequence'), 'WY_STATE_FUEL', 'WY State Fuel', 'fuelTaxCalculator', 'FUEL_STATE', '56', 6)
;

-- tax_rate_state_fuel.sql
INSERT INTO public.tax_rate(
            id, tax_definition_key, rate, range_low, range_high)
    VALUES
    (nextval('public.hibernate_sequence'), 'US_FEDERAL_FUEL', 0.184, null, null),
    (nextval('public.hibernate_sequence'), 'AL_STATE_FUEL', 0.2109, null, null),
    (nextval('public.hibernate_sequence'), 'AZ_STATE_FUEL', 0.19, null, null),
    (nextval('public.hibernate_sequence'), 'AK_STATE_FUEL', 0.1444, null, null),
    (nextval('public.hibernate_sequence'), 'AR_STATE_FUEL', 0.2180, null, null),
    (nextval('public.hibernate_sequence'), 'CA_STATE_FUEL', 0.5436, null, null),
    (nextval('public.hibernate_sequence'), 'CO_STATE_FUEL', 0.22, null, null),
    (nextval('public.hibernate_sequence'), 'CT_STATE_FUEL', 0.3685, null, null),
    (nextval('public.hibernate_sequence'), 'DE_STATE_FUEL', 0.23, null, null),
    (nextval('public.hibernate_sequence'), 'DC_STATE_FUEL', 0.2350, null, null),
    (nextval('public.hibernate_sequence'), 'FL_STATE_FUEL', 0.4199, null, null),
    (nextval('public.hibernate_sequence'), 'GA_STATE_FUEL', 0.3528, null, null),
    (nextval('public.hibernate_sequence'), 'HI_STATE_FUEL', 0.4638, null, null),
    (nextval('public.hibernate_sequence'), 'ID_STATE_FUEL', 0.33, null, null),
    (nextval('public.hibernate_sequence'), 'IL_STATE_FUEL', 0.3198, null, null),
    (nextval('public.hibernate_sequence'), 'IN_STATE_FUEL', 0.4290, null, null),
    (nextval('public.hibernate_sequence'), 'IA_STATE_FUEL', 0.3070, null, null),
    (nextval('public.hibernate_sequence'), 'KS_STATE_FUEL', 0.2403, null, null),
    (nextval('public.hibernate_sequence'), 'KY_STATE_FUEL', 0.26, null, null),
    (nextval('public.hibernate_sequence'), 'LA_STATE_FUEL', 0.2001, null, null),
    (nextval('public.hibernate_sequence'), 'ME_STATE_FUEL', 0.3001, null, null),
    (nextval('public.hibernate_sequence'), 'MD_STATE_FUEL', 0.3530, null, null),
    (nextval('public.hibernate_sequence'), 'MA_STATE_FUEL', 0.2654, null, null),
    (nextval('public.hibernate_sequence'), 'MI_STATE_FUEL', 0.3841, null, null),
    (nextval('public.hibernate_sequence'), 'MN_STATE_FUEL', 0.2860, null, null),
    (nextval('public.hibernate_sequence'), 'MS_STATE_FUEL', 0.1879, null, null),
    (nextval('public.hibernate_sequence'), 'MO_STATE_FUEL', 0.1735, null, null),
    (nextval('public.hibernate_sequence'), 'MT_STATE_FUEL', 0.3225, null, null),
    (nextval('public.hibernate_sequence'), 'NE_STATE_FUEL', 0.3050, null, null),
    (nextval('public.hibernate_sequence'), 'NV_STATE_FUEL', 0.3378, null, null),
    (nextval('public.hibernate_sequence'), 'NH_STATE_FUEL', 0.2383, null, null),
    (nextval('public.hibernate_sequence'), 'NJ_STATE_FUEL', 0.4140, null, null),
    (nextval('public.hibernate_sequence'), 'NM_STATE_FUEL', 0.1888, null, null),
    (nextval('public.hibernate_sequence'), 'NY_STATE_FUEL', 0.4410, null, null),
    (nextval('public.hibernate_sequence'), 'NC_STATE_FUEL', 0.3645, null, null),
    (nextval('public.hibernate_sequence'), 'ND_STATE_FUEL', 0.23, null, null),
    (nextval('public.hibernate_sequence'), 'OH_STATE_FUEL', 0.2801, null, null),
    (nextval('public.hibernate_sequence'), 'OK_STATE_FUEL', 0.20, null, null),
    (nextval('public.hibernate_sequence'), 'OR_STATE_FUEL', 0.3677, null, null),
    (nextval('public.hibernate_sequence'), 'PA_STATE_FUEL', 0.5870, null, null),
    (nextval('public.hibernate_sequence'), 'RI_STATE_FUEL', 0.34, null, null),
    (nextval('public.hibernate_sequence'), 'SC_STATE_FUEL', 0.2075, null, null),
    (nextval('public.hibernate_sequence'), 'SD_STATE_FUEL', 0.30, null, null),
    (nextval('public.hibernate_sequence'), 'TN_STATE_FUEL', 0.2540, null, null),
    (nextval('public.hibernate_sequence'), 'TX_STATE_FUEL', 0.20, null, null),
    (nextval('public.hibernate_sequence'), 'UT_STATE_FUEL', 0.3001, null, null),
    (nextval('public.hibernate_sequence'), 'VT_STATE_FUEL', 0.3119, null, null),
    (nextval('public.hibernate_sequence'), 'VA_STATE_FUEL', 0.2066, null, null),
    (nextval('public.hibernate_sequence'), 'WA_STATE_FUEL', 0.4940, null, null),
    (nextval('public.hibernate_sequence'), 'WV_STATE_FUEL', 0.3570, null, null),
    (nextval('public.hibernate_sequence'), 'WI_STATE_FUEL', 0.3290, null, null),
    (nextval('public.hibernate_sequence'), 'WY_STATE_FUEL', 0.24, null, null)
;
