INSERT INTO public.political_division 
  (id, 
  fips,
  description,
  name,
  type 
  )
VALUES
(nextval('public.hibernate_sequence'),'13001','Appling County','Appling County','COUNTY'),
(nextval('public.hibernate_sequence'),'13003','Atkinson County','Atkinson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13005','Bacon County','Bacon County','COUNTY'),
(nextval('public.hibernate_sequence'),'13007','Baker County','Baker County','COUNTY'),
(nextval('public.hibernate_sequence'),'13009','Baldwin County','Baldwin County','COUNTY'),
(nextval('public.hibernate_sequence'),'13011','Banks County','Banks County','COUNTY'),
(nextval('public.hibernate_sequence'),'13013','Barrow County','Barrow County','COUNTY'),
(nextval('public.hibernate_sequence'),'13015','Bartow County','Bartow County','COUNTY'),
(nextval('public.hibernate_sequence'),'13017','Ben Hill County','Ben Hill County','COUNTY'),
(nextval('public.hibernate_sequence'),'13019','Berrien County','Berrien County','COUNTY'),
(nextval('public.hibernate_sequence'),'13021','Bibb County','Bibb County','COUNTY'),
(nextval('public.hibernate_sequence'),'13023','Bleckley County','Bleckley County','COUNTY'),
(nextval('public.hibernate_sequence'),'13025','Brantley County','Brantley County','COUNTY'),
(nextval('public.hibernate_sequence'),'13027','Brooks County','Brooks County','COUNTY'),
(nextval('public.hibernate_sequence'),'13029','Bryan County','Bryan County','COUNTY'),
(nextval('public.hibernate_sequence'),'13031','Bulloch County','Bulloch County','COUNTY'),
(nextval('public.hibernate_sequence'),'13033','Burke County','Burke County','COUNTY'),
(nextval('public.hibernate_sequence'),'13035','Butts County','Butts County','COUNTY'),
(nextval('public.hibernate_sequence'),'13037','Calhoun County','Calhoun County','COUNTY'),
(nextval('public.hibernate_sequence'),'13039','Camden County','Camden County','COUNTY'),
(nextval('public.hibernate_sequence'),'13043','Candler County','Candler County','COUNTY'),
(nextval('public.hibernate_sequence'),'13045','Carroll County','Carroll County','COUNTY'),
(nextval('public.hibernate_sequence'),'13047','Catoosa County','Catoosa County','COUNTY'),
(nextval('public.hibernate_sequence'),'13049','Charlton County','Charlton County','COUNTY'),
(nextval('public.hibernate_sequence'),'13051','Chatham County','Chatham County','COUNTY'),
(nextval('public.hibernate_sequence'),'13053','Chattahoochee County','Chattahoochee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13055','Chattooga County','Chattooga County','COUNTY'),
(nextval('public.hibernate_sequence'),'13057','Cherokee County','Cherokee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13059','Clarke County','Clarke County','COUNTY'),
(nextval('public.hibernate_sequence'),'13061','Clay County','Clay County','COUNTY'),
(nextval('public.hibernate_sequence'),'13063','Clayton County','Clayton County','COUNTY'),
(nextval('public.hibernate_sequence'),'13065','Clinch County','Clinch County','COUNTY'),
(nextval('public.hibernate_sequence'),'13067','Cobb County','Cobb County','COUNTY'),
(nextval('public.hibernate_sequence'),'13069','Coffee County','Coffee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13071','Colquitt County','Colquitt County','COUNTY'),
(nextval('public.hibernate_sequence'),'13073','Columbia County','Columbia County','COUNTY'),
(nextval('public.hibernate_sequence'),'13075','Cook County','Cook County','COUNTY'),
(nextval('public.hibernate_sequence'),'13077','Coweta County','Coweta County','COUNTY'),
(nextval('public.hibernate_sequence'),'13079','Crawford County','Crawford County','COUNTY'),
(nextval('public.hibernate_sequence'),'13081','Crisp County','Crisp County','COUNTY'),
(nextval('public.hibernate_sequence'),'13083','Dade County','Dade County','COUNTY'),
(nextval('public.hibernate_sequence'),'13085','Dawson County','Dawson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13087','Decatur County','Decatur County','COUNTY'),
(nextval('public.hibernate_sequence'),'13089','DeKalb County','DeKalb County','COUNTY'),
(nextval('public.hibernate_sequence'),'13091','Dodge County','Dodge County','COUNTY'),
(nextval('public.hibernate_sequence'),'13093','Dooly County','Dooly County','COUNTY'),
(nextval('public.hibernate_sequence'),'13095','Dougherty County','Dougherty County','COUNTY'),
(nextval('public.hibernate_sequence'),'13097','Douglas County','Douglas County','COUNTY'),
(nextval('public.hibernate_sequence'),'13099','Early County','Early County','COUNTY'),
(nextval('public.hibernate_sequence'),'13101','Echols County','Echols County','COUNTY'),
(nextval('public.hibernate_sequence'),'13103','Effingham County','Effingham County','COUNTY'),
(nextval('public.hibernate_sequence'),'13105','Elbert County','Elbert County','COUNTY'),
(nextval('public.hibernate_sequence'),'13107','Emanuel County','Emanuel County','COUNTY'),
(nextval('public.hibernate_sequence'),'13109','Evans County','Evans County','COUNTY'),
(nextval('public.hibernate_sequence'),'13111','Fannin County','Fannin County','COUNTY'),
(nextval('public.hibernate_sequence'),'13113','Fayette County','Fayette County','COUNTY'),
(nextval('public.hibernate_sequence'),'13115','Floyd County','Floyd County','COUNTY'),
(nextval('public.hibernate_sequence'),'13117','Forsyth County','Forsyth County','COUNTY'),
(nextval('public.hibernate_sequence'),'13119','Franklin County','Franklin County','COUNTY'),
(nextval('public.hibernate_sequence'),'13121','Fulton County','Fulton County','COUNTY'),
(nextval('public.hibernate_sequence'),'13123','Gilmer County','Gilmer County','COUNTY'),
(nextval('public.hibernate_sequence'),'13125','Glascock County','Glascock County','COUNTY'),
(nextval('public.hibernate_sequence'),'13127','Glynn County','Glynn County','COUNTY'),
(nextval('public.hibernate_sequence'),'13129','Gordon County','Gordon County','COUNTY'),
(nextval('public.hibernate_sequence'),'13131','Grady County','Grady County','COUNTY'),
(nextval('public.hibernate_sequence'),'13133','Greene County','Greene County','COUNTY'),
(nextval('public.hibernate_sequence'),'13135','Gwinnett County','Gwinnett County','COUNTY'),
(nextval('public.hibernate_sequence'),'13137','Habersham County','Habersham County','COUNTY'),
(nextval('public.hibernate_sequence'),'13139','Hall County','Hall County','COUNTY'),
(nextval('public.hibernate_sequence'),'13141','Hancock County','Hancock County','COUNTY'),
(nextval('public.hibernate_sequence'),'13143','Haralson County','Haralson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13145','Harris County','Harris County','COUNTY'),
(nextval('public.hibernate_sequence'),'13147','Hart County','Hart County','COUNTY'),
(nextval('public.hibernate_sequence'),'13149','Heard County','Heard County','COUNTY'),
(nextval('public.hibernate_sequence'),'13151','Henry County','Henry County','COUNTY'),
(nextval('public.hibernate_sequence'),'13153','Houston County','Houston County','COUNTY'),
(nextval('public.hibernate_sequence'),'13155','Irwin County','Irwin County','COUNTY'),
(nextval('public.hibernate_sequence'),'13157','Jackson County','Jackson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13159','Jasper County','Jasper County','COUNTY'),
(nextval('public.hibernate_sequence'),'13161','Jeff Davis County','Jeff Davis County','COUNTY'),
(nextval('public.hibernate_sequence'),'13163','Jefferson County','Jefferson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13165','Jenkins County','Jenkins County','COUNTY'),
(nextval('public.hibernate_sequence'),'13167','Johnson County','Johnson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13169','Jones County','Jones County','COUNTY'),
(nextval('public.hibernate_sequence'),'13171','Lamar County','Lamar County','COUNTY'),
(nextval('public.hibernate_sequence'),'13173','Lanier County','Lanier County','COUNTY'),
(nextval('public.hibernate_sequence'),'13175','Laurens County','Laurens County','COUNTY'),
(nextval('public.hibernate_sequence'),'13177','Lee County','Lee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13179','Liberty County','Liberty County','COUNTY'),
(nextval('public.hibernate_sequence'),'13181','Lincoln County','Lincoln County','COUNTY'),
(nextval('public.hibernate_sequence'),'13183','Long County','Long County','COUNTY'),
(nextval('public.hibernate_sequence'),'13185','Lowndes County','Lowndes County','COUNTY'),
(nextval('public.hibernate_sequence'),'13187','Lumpkin County','Lumpkin County','COUNTY'),
(nextval('public.hibernate_sequence'),'13189','McDuffie County','McDuffie County','COUNTY'),
(nextval('public.hibernate_sequence'),'13191','McIntosh County','McIntosh County','COUNTY'),
(nextval('public.hibernate_sequence'),'13193','Macon County','Macon County','COUNTY'),
(nextval('public.hibernate_sequence'),'13195','Madison County','Madison County','COUNTY'),
(nextval('public.hibernate_sequence'),'13197','Marion County','Marion County','COUNTY'),
(nextval('public.hibernate_sequence'),'13199','Meriwether County','Meriwether County','COUNTY'),
(nextval('public.hibernate_sequence'),'13201','Miller County','Miller County','COUNTY'),
(nextval('public.hibernate_sequence'),'13205','Mitchell County','Mitchell County','COUNTY'),
(nextval('public.hibernate_sequence'),'13207','Monroe County','Monroe County','COUNTY'),
(nextval('public.hibernate_sequence'),'13209','Montgomery County','Montgomery County','COUNTY'),
(nextval('public.hibernate_sequence'),'13211','Morgan County','Morgan County','COUNTY'),
(nextval('public.hibernate_sequence'),'13213','Murray County','Murray County','COUNTY'),
(nextval('public.hibernate_sequence'),'13215','Muscogee County','Muscogee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13217','Newton County','Newton County','COUNTY'),
(nextval('public.hibernate_sequence'),'13219','Oconee County','Oconee County','COUNTY'),
(nextval('public.hibernate_sequence'),'13221','Oglethorpe County','Oglethorpe County','COUNTY'),
(nextval('public.hibernate_sequence'),'13223','Paulding County','Paulding County','COUNTY'),
(nextval('public.hibernate_sequence'),'13225','Peach County','Peach County','COUNTY'),
(nextval('public.hibernate_sequence'),'13227','Pickens County','Pickens County','COUNTY'),
(nextval('public.hibernate_sequence'),'13229','Pierce County','Pierce County','COUNTY'),
(nextval('public.hibernate_sequence'),'13231','Pike County','Pike County','COUNTY'),
(nextval('public.hibernate_sequence'),'13233','Polk County','Polk County','COUNTY'),
(nextval('public.hibernate_sequence'),'13235','Pulaski County','Pulaski County','COUNTY'),
(nextval('public.hibernate_sequence'),'13237','Putnam County','Putnam County','COUNTY'),
(nextval('public.hibernate_sequence'),'13239','Quitman County','Quitman County','COUNTY'),
(nextval('public.hibernate_sequence'),'13241','Rabun County','Rabun County','COUNTY'),
(nextval('public.hibernate_sequence'),'13243','Randolph County','Randolph County','COUNTY'),
(nextval('public.hibernate_sequence'),'13245','Richmond County','Richmond County','COUNTY'),
(nextval('public.hibernate_sequence'),'13247','Rockdale County','Rockdale County','COUNTY'),
(nextval('public.hibernate_sequence'),'13249','Schley County','Schley County','COUNTY'),
(nextval('public.hibernate_sequence'),'13251','Screven County','Screven County','COUNTY'),
(nextval('public.hibernate_sequence'),'13253','Seminole County','Seminole County','COUNTY'),
(nextval('public.hibernate_sequence'),'13255','Spalding County','Spalding County','COUNTY'),
(nextval('public.hibernate_sequence'),'13257','Stephens County','Stephens County','COUNTY'),
(nextval('public.hibernate_sequence'),'13259','Stewart County','Stewart County','COUNTY'),
(nextval('public.hibernate_sequence'),'13261','Sumter County','Sumter County','COUNTY'),
(nextval('public.hibernate_sequence'),'13263','Talbot County','Talbot County','COUNTY'),
(nextval('public.hibernate_sequence'),'13265','Taliaferro County','Taliaferro County','COUNTY'),
(nextval('public.hibernate_sequence'),'13267','Tattnall County','Tattnall County','COUNTY'),
(nextval('public.hibernate_sequence'),'13269','Taylor County','Taylor County','COUNTY'),
(nextval('public.hibernate_sequence'),'13271','Telfair County','Telfair County','COUNTY'),
(nextval('public.hibernate_sequence'),'13273','Terrell County','Terrell County','COUNTY'),
(nextval('public.hibernate_sequence'),'13275','Thomas County','Thomas County','COUNTY'),
(nextval('public.hibernate_sequence'),'13277','Tift County','Tift County','COUNTY'),
(nextval('public.hibernate_sequence'),'13279','Toombs County','Toombs County','COUNTY'),
(nextval('public.hibernate_sequence'),'13281','Towns County','Towns County','COUNTY'),
(nextval('public.hibernate_sequence'),'13283','Treutlen County','Treutlen County','COUNTY'),
(nextval('public.hibernate_sequence'),'13285','Troup County','Troup County','COUNTY'),
(nextval('public.hibernate_sequence'),'13287','Turner County','Turner County','COUNTY'),
(nextval('public.hibernate_sequence'),'13289','Twiggs County','Twiggs County','COUNTY'),
(nextval('public.hibernate_sequence'),'13291','Union County','Union County','COUNTY'),
(nextval('public.hibernate_sequence'),'13293','Upson County','Upson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13295','Walker County','Walker County','COUNTY'),
(nextval('public.hibernate_sequence'),'13297','Walton County','Walton County','COUNTY'),
(nextval('public.hibernate_sequence'),'13299','Ware County','Ware County','COUNTY'),
(nextval('public.hibernate_sequence'),'13301','Warren County','Warren County','COUNTY'),
(nextval('public.hibernate_sequence'),'13303','Washington County','Washington County','COUNTY'),
(nextval('public.hibernate_sequence'),'13305','Wayne County','Wayne County','COUNTY'),
(nextval('public.hibernate_sequence'),'13307','Webster County','Webster County','COUNTY'),
(nextval('public.hibernate_sequence'),'13309','Wheeler County','Wheeler County','COUNTY'),
(nextval('public.hibernate_sequence'),'13311','White County','White County','COUNTY'),
(nextval('public.hibernate_sequence'),'13313','Whitfield County','Whitfield County','COUNTY'),
(nextval('public.hibernate_sequence'),'13315','Wilcox County','Wilcox County','COUNTY'),
(nextval('public.hibernate_sequence'),'13317','Wilkes County','Wilkes County','COUNTY'),
(nextval('public.hibernate_sequence'),'13319','Wilkinson County','Wilkinson County','COUNTY'),
(nextval('public.hibernate_sequence'),'13321','Worth County','Worth County','COUNTY'),
(nextval('public.hibernate_sequence'),'1300184','Abbeville city','Abbeville city','CITY'),
(nextval('public.hibernate_sequence'),'1300408','Acworth city','Acworth city','CITY'),
(nextval('public.hibernate_sequence'),'1300436','Adairsville city','Adairsville city','CITY'),
(nextval('public.hibernate_sequence'),'1300576','Adel city','Adel city','CITY'),
(nextval('public.hibernate_sequence'),'1300660','Adrian city','Adrian city','CITY'),
(nextval('public.hibernate_sequence'),'1300828','Ailey city','Ailey city','CITY'),
(nextval('public.hibernate_sequence'),'1300996','Alamo town','Alamo town','CITY'),
(nextval('public.hibernate_sequence'),'1301024','Alapaha town','Alapaha town','CITY'),
(nextval('public.hibernate_sequence'),'1301052','Albany city','Albany city','CITY'),
(nextval('public.hibernate_sequence'),'1301248','Aldora town','Aldora town','CITY'),
(nextval('public.hibernate_sequence'),'1301472','Allenhurst city','Allenhurst city','CITY'),
(nextval('public.hibernate_sequence'),'1301500','Allentown city','Allentown city','CITY'),
(nextval('public.hibernate_sequence'),'1301612','Alma city','Alma city','CITY'),
(nextval('public.hibernate_sequence'),'1301696','Alpharetta city','Alpharetta city','CITY'),
(nextval('public.hibernate_sequence'),'1301808','Alston town','Alston town','CITY'),
(nextval('public.hibernate_sequence'),'1301948','Alto town','Alto town','CITY'),
(nextval('public.hibernate_sequence'),'1302060','Ambrose city','Ambrose city','CITY'),
(nextval('public.hibernate_sequence'),'1302116','Americus city','Americus city','CITY'),
(nextval('public.hibernate_sequence'),'1302256','Andersonville city','Andersonville city','CITY'),
(nextval('public.hibernate_sequence'),'1302564','Arabi town','Arabi town','CITY'),
(nextval('public.hibernate_sequence'),'1302592','Aragon city','Aragon city','CITY'),
(nextval('public.hibernate_sequence'),'1302648','Arcade city','Arcade city','CITY'),
(nextval('public.hibernate_sequence'),'1302844','Argyle town','Argyle town','CITY'),
(nextval('public.hibernate_sequence'),'1302928','Arlington city','Arlington city','CITY'),
(nextval('public.hibernate_sequence'),'1303124','Arnoldsville city','Arnoldsville city','CITY'),
(nextval('public.hibernate_sequence'),'1303236','Ashburn city','Ashburn city','CITY'),
(nextval('public.hibernate_sequence'),'1303440','Athens-Clarke County unified government (balance)','Athens-Clarke County unified government (balance)','CITY'),
(nextval('public.hibernate_sequence'),'1304000','Atlanta city','Atlanta city','CITY'),
(nextval('public.hibernate_sequence'),'1304084','Attapulgus city','Attapulgus city','CITY'),
(nextval('public.hibernate_sequence'),'1304140','Auburn city','Auburn city','CITY'),
(nextval('public.hibernate_sequence'),'1304204','Augusta-Richmond County consolidated government (balance)','Augusta-Richmond County consolidated government (balance)','CITY'),
(nextval('public.hibernate_sequence'),'1304252','Austell city','Austell city','CITY'),
(nextval('public.hibernate_sequence'),'1304392','Avalon town','Avalon town','CITY'),
(nextval('public.hibernate_sequence'),'1304448','Avera city','Avera city','CITY'),
(nextval('public.hibernate_sequence'),'1304644','Avondale Estates city','Avondale Estates city','CITY'),
(nextval('public.hibernate_sequence'),'1304840','Baconton city','Baconton city','CITY'),
(nextval('public.hibernate_sequence'),'1304896','Bainbridge city','Bainbridge city','CITY'),
(nextval('public.hibernate_sequence'),'1304980','Baldwin city','Baldwin city','CITY'),
(nextval('public.hibernate_sequence'),'1305036','Ball Ground city','Ball Ground city','CITY'),
(nextval('public.hibernate_sequence'),'1305344','Barnesville city','Barnesville city','CITY'),
(nextval('public.hibernate_sequence'),'1305680','Bartow town','Bartow town','CITY'),
(nextval('public.hibernate_sequence'),'1305708','Barwick city','Barwick city','CITY'),
(nextval('public.hibernate_sequence'),'1306016','Baxley city','Baxley city','CITY'),
(nextval('public.hibernate_sequence'),'1306688','Bellville city','Bellville city','CITY'),
(nextval('public.hibernate_sequence'),'1306884','Belvedere Park CDP','Belvedere Park CDP','CITY'),
(nextval('public.hibernate_sequence'),'1307248','Berkeley Lake city','Berkeley Lake city','CITY'),
(nextval('public.hibernate_sequence'),'1307304','Berlin city','Berlin city','CITY'),
(nextval('public.hibernate_sequence'),'1307612','Bethlehem town','Bethlehem town','CITY'),
(nextval('public.hibernate_sequence'),'1307640','Between town','Between town','CITY'),
(nextval('public.hibernate_sequence'),'1308200','Bishop town','Bishop town','CITY'),
(nextval('public.hibernate_sequence'),'1308284','Blackshear city','Blackshear city','CITY'),
(nextval('public.hibernate_sequence'),'1308480','Blairsville city','Blairsville city','CITY'),
(nextval('public.hibernate_sequence'),'1308536','Blakely city','Blakely city','CITY'),
(nextval('public.hibernate_sequence'),'1308844','Bloomingdale city','Bloomingdale city','CITY'),
(nextval('public.hibernate_sequence'),'1308928','Blue Ridge city','Blue Ridge city','CITY'),
(nextval('public.hibernate_sequence'),'1308956','Bluffton town','Bluffton town','CITY'),
(nextval('public.hibernate_sequence'),'1309040','Blythe city','Blythe city','CITY'),
(nextval('public.hibernate_sequence'),'1309068','Bogart town','Bogart town','CITY'),
(nextval('public.hibernate_sequence'),'1309272','Bonanza CDP','Bonanza CDP','CITY'),
(nextval('public.hibernate_sequence'),'1309460','Boston city','Boston city','CITY'),
(nextval('public.hibernate_sequence'),'1309488','Bostwick city','Bostwick city','CITY'),
(nextval('public.hibernate_sequence'),'1309544','Bowdon city','Bowdon city','CITY'),
(nextval('public.hibernate_sequence'),'1309656','Bowersville town','Bowersville town','CITY'),
(nextval('public.hibernate_sequence'),'1309712','Bowman city','Bowman city','CITY'),
(nextval('public.hibernate_sequence'),'1309852','Boykin CDP','Boykin CDP','CITY'),
(nextval('public.hibernate_sequence'),'1310076','Braselton town','Braselton town','CITY'),
(nextval('public.hibernate_sequence'),'1310104','Braswell town','Braswell town','CITY'),
(nextval('public.hibernate_sequence'),'1310132','Bremen city','Bremen city','CITY'),
(nextval('public.hibernate_sequence'),'1310608','Brinson town','Brinson town','CITY'),
(nextval('public.hibernate_sequence'),'1310860','Bronwood town','Bronwood town','CITY'),
(nextval('public.hibernate_sequence'),'1311000','Brooklet city','Brooklet city','CITY'),
(nextval('public.hibernate_sequence'),'1311056','Brooks town','Brooks town','CITY'),
(nextval('public.hibernate_sequence'),'1311504','Broxton city','Broxton city','CITY'),
(nextval('public.hibernate_sequence'),'1311560','Brunswick city','Brunswick city','CITY'),
(nextval('public.hibernate_sequence'),'1311616','Buchanan city','Buchanan city','CITY'),
(nextval('public.hibernate_sequence'),'1311672','Buckhead town','Buckhead town','CITY'),
(nextval('public.hibernate_sequence'),'1311728','Buena Vista city','Buena Vista city','CITY'),
(nextval('public.hibernate_sequence'),'1311784','Buford city','Buford city','CITY'),
(nextval('public.hibernate_sequence'),'1312120','Butler city','Butler city','CITY'),
(nextval('public.hibernate_sequence'),'1312232','Byromville town','Byromville town','CITY'),
(nextval('public.hibernate_sequence'),'1312260','Byron city','Byron city','CITY'),
(nextval('public.hibernate_sequence'),'1312344','Cadwell town','Cadwell town','CITY'),
(nextval('public.hibernate_sequence'),'1312400','Cairo city','Cairo city','CITY'),
(nextval('public.hibernate_sequence'),'1312456','Calhoun city','Calhoun city','CITY'),
(nextval('public.hibernate_sequence'),'1312484','Calvary CDP','Calvary CDP','CITY'),
(nextval('public.hibernate_sequence'),'1312512','Camak town','Camak town','CITY'),
(nextval('public.hibernate_sequence'),'1312624','Camilla city','Camilla city','CITY'),
(nextval('public.hibernate_sequence'),'1312834','Candler-McAfee CDP','Candler-McAfee CDP','CITY'),
(nextval('public.hibernate_sequence'),'1312932','Canon city','Canon city','CITY'),
(nextval('public.hibernate_sequence'),'1312960','Canoochee CDP','Canoochee CDP','CITY'),
(nextval('public.hibernate_sequence'),'1312988','Canton city','Canton city','CITY'),
(nextval('public.hibernate_sequence'),'1313184','Carl town','Carl town','CITY'),
(nextval('public.hibernate_sequence'),'1313212','Carlton city','Carlton city','CITY'),
(nextval('public.hibernate_sequence'),'1313352','Carnesville city','Carnesville city','CITY'),
(nextval('public.hibernate_sequence'),'1313492','Carrollton city','Carrollton city','CITY'),
(nextval('public.hibernate_sequence'),'1313688','Cartersville city','Cartersville city','CITY'),
(nextval('public.hibernate_sequence'),'1314108','Cave Spring city','Cave Spring city','CITY'),
(nextval('public.hibernate_sequence'),'1314192','Cecil city','Cecil city','CITY'),
(nextval('public.hibernate_sequence'),'1314472','Cedar Springs CDP','Cedar Springs CDP','CITY'),
(nextval('public.hibernate_sequence'),'1314500','Cedartown city','Cedartown city','CITY'),
(nextval('public.hibernate_sequence'),'1314920','Centerville city','Centerville city','CITY'),
(nextval('public.hibernate_sequence'),'1315026','Centralhatchee town','Centralhatchee town','CITY'),
(nextval('public.hibernate_sequence'),'1315172','Chamblee city','Chamblee city','CITY'),
(nextval('public.hibernate_sequence'),'1315508','Chatsworth city','Chatsworth city','CITY'),
(nextval('public.hibernate_sequence'),'1315552','Chattahoochee Hills city','Chattahoochee Hills city','CITY'),
(nextval('public.hibernate_sequence'),'1315585','Chattanooga Valley CDP','Chattanooga Valley CDP','CITY'),
(nextval('public.hibernate_sequence'),'1315648','Chauncey city','Chauncey city','CITY'),
(nextval('public.hibernate_sequence'),'1315844','Cherry Log CDP','Cherry Log CDP','CITY'),
(nextval('public.hibernate_sequence'),'1315900','Chester town','Chester town','CITY'),
(nextval('public.hibernate_sequence'),'1315984','Chickamauga city','Chickamauga city','CITY'),
(nextval('public.hibernate_sequence'),'1316460','Clarkesville city','Clarkesville city','CITY'),
(nextval('public.hibernate_sequence'),'1316544','Clarkston city','Clarkston city','CITY'),
(nextval('public.hibernate_sequence'),'1316600','Claxton city','Claxton city','CITY'),
(nextval('public.hibernate_sequence'),'1316656','Clayton city','Clayton city','CITY'),
(nextval('public.hibernate_sequence'),'1316796','Clermont town','Clermont town','CITY'),
(nextval('public.hibernate_sequence'),'1316824','Cleveland city','Cleveland city','CITY'),
(nextval('public.hibernate_sequence'),'1316908','Climax city','Climax city','CITY'),
(nextval('public.hibernate_sequence'),'1317272','Cobbtown city','Cobbtown city','CITY'),
(nextval('public.hibernate_sequence'),'1317328','Cochran city','Cochran city','CITY'),
(nextval('public.hibernate_sequence'),'1317496','Cohutta city','Cohutta city','CITY'),
(nextval('public.hibernate_sequence'),'1317552','Colbert city','Colbert city','CITY'),
(nextval('public.hibernate_sequence'),'1317580','Coleman CDP','Coleman CDP','CITY'),
(nextval('public.hibernate_sequence'),'1317776','College Park city','College Park city','CITY'),
(nextval('public.hibernate_sequence'),'1317832','Collins city','Collins city','CITY'),
(nextval('public.hibernate_sequence'),'1318000','Colquitt city','Colquitt city','CITY'),
(nextval('public.hibernate_sequence'),'1319000','Columbus city','Columbus city','CITY'),
(nextval('public.hibernate_sequence'),'1319084','Comer city','Comer city','CITY'),
(nextval('public.hibernate_sequence'),'1319112','Commerce city','Commerce city','CITY'),
(nextval('public.hibernate_sequence'),'1319168','Concord city','Concord city','CITY'),
(nextval('public.hibernate_sequence'),'1319280','Conley CDP','Conley CDP','CITY'),
(nextval('public.hibernate_sequence'),'1319336','Conyers city','Conyers city','CITY'),
(nextval('public.hibernate_sequence'),'1319392','Coolidge city','Coolidge city','CITY'),
(nextval('public.hibernate_sequence'),'1319616','Cordele city','Cordele city','CITY'),
(nextval('public.hibernate_sequence'),'1319728','Cornelia city','Cornelia city','CITY'),
(nextval('public.hibernate_sequence'),'1319830','Country Club Estates CDP','Country Club Estates CDP','CITY'),
(nextval('public.hibernate_sequence'),'1320064','Covington city','Covington city','CITY'),
(nextval('public.hibernate_sequence'),'1320288','Crawford city','Crawford city','CITY'),
(nextval('public.hibernate_sequence'),'1320316','Crawfordville city','Crawfordville city','CITY'),
(nextval('public.hibernate_sequence'),'1320550','Crooked Creek CDP','Crooked Creek CDP','CITY'),
(nextval('public.hibernate_sequence'),'1320848','Culloden city','Culloden city','CITY'),
(nextval('public.hibernate_sequence'),'1320932','Cumming city','Cumming city','CITY'),
(nextval('public.hibernate_sequence'),'1321017','Cusseta-Chattahoochee County unified government','Cusseta-Chattahoochee County unified government','CITY'),
(nextval('public.hibernate_sequence'),'1321072','Cuthbert city','Cuthbert city','CITY'),
(nextval('public.hibernate_sequence'),'1321184','Dacula city','Dacula city','CITY'),
(nextval('public.hibernate_sequence'),'1321240','Dahlonega city','Dahlonega city','CITY'),
(nextval('public.hibernate_sequence'),'1321268','Daisy city','Daisy city','CITY'),
(nextval('public.hibernate_sequence'),'1321324','Dallas city','Dallas city','CITY'),
(nextval('public.hibernate_sequence'),'1321380','Dalton city','Dalton city','CITY'),
(nextval('public.hibernate_sequence'),'1321436','Damascus city','Damascus city','CITY'),
(nextval('public.hibernate_sequence'),'1321632','Danielsville city','Danielsville city','CITY'),
(nextval('public.hibernate_sequence'),'1321688','Danville town','Danville town','CITY'),
(nextval('public.hibernate_sequence'),'1321716','Darien city','Darien city','CITY'),
(nextval('public.hibernate_sequence'),'1321744','Dasher town','Dasher town','CITY'),
(nextval('public.hibernate_sequence'),'1321800','Davisboro city','Davisboro city','CITY'),
(nextval('public.hibernate_sequence'),'1321912','Dawson city','Dawson city','CITY'),
(nextval('public.hibernate_sequence'),'1321940','Dawsonville city','Dawsonville city','CITY'),
(nextval('public.hibernate_sequence'),'1322024','Dearing town','Dearing town','CITY'),
(nextval('public.hibernate_sequence'),'1322052','Decatur city','Decatur city','CITY'),
(nextval('public.hibernate_sequence'),'1322080','Deenwood CDP','Deenwood CDP','CITY'),
(nextval('public.hibernate_sequence'),'1322108','Deepstep town','Deepstep town','CITY'),
(nextval('public.hibernate_sequence'),'1322304','Demorest city','Demorest city','CITY'),
(nextval('public.hibernate_sequence'),'1322388','Denton city','Denton city','CITY'),
(nextval('public.hibernate_sequence'),'1322472','De Soto city','De Soto city','CITY'),
(nextval('public.hibernate_sequence'),'1322724','Dewy Rose CDP','Dewy Rose CDP','CITY'),
(nextval('public.hibernate_sequence'),'1322752','Dexter town','Dexter town','CITY'),
(nextval('public.hibernate_sequence'),'1322976','Dillard city','Dillard city','CITY'),
(nextval('public.hibernate_sequence'),'1323200','Dock Junction CDP','Dock Junction CDP','CITY'),
(nextval('public.hibernate_sequence'),'1323284','Doerun city','Doerun city','CITY'),
(nextval('public.hibernate_sequence'),'1323368','Donalsonville city','Donalsonville city','CITY'),
(nextval('public.hibernate_sequence'),'1323480','Dooling town','Dooling town','CITY'),
(nextval('public.hibernate_sequence'),'1323536','Doraville city','Doraville city','CITY'),
(nextval('public.hibernate_sequence'),'1323872','Douglas city','Douglas city','CITY'),
(nextval('public.hibernate_sequence'),'1323900','Douglasville city','Douglasville city','CITY'),
(nextval('public.hibernate_sequence'),'1324264','Druid Hills CDP','Druid Hills CDP','CITY'),
(nextval('public.hibernate_sequence'),'1324376','Dublin city','Dublin city','CITY'),
(nextval('public.hibernate_sequence'),'1324488','Dudley city','Dudley city','CITY'),
(nextval('public.hibernate_sequence'),'1324600','Duluth city','Duluth city','CITY'),
(nextval('public.hibernate_sequence'),'1324768','Dunwoody city','Dunwoody city','CITY'),
(nextval('public.hibernate_sequence'),'1324796','Du Pont town','Du Pont town','CITY'),
(nextval('public.hibernate_sequence'),'1324876','Dutch Island CDP','Dutch Island CDP','CITY'),
(nextval('public.hibernate_sequence'),'1324964','Eagle Grove CDP','Eagle Grove CDP','CITY'),
(nextval('public.hibernate_sequence'),'1325300','East Dublin city','East Dublin city','CITY'),
(nextval('public.hibernate_sequence'),'1325356','East Ellijay city','East Ellijay city','CITY'),
(nextval('public.hibernate_sequence'),'1325440','East Griffin CDP','East Griffin CDP','CITY'),
(nextval('public.hibernate_sequence'),'1325552','Eastman city','Eastman city','CITY'),
(nextval('public.hibernate_sequence'),'1325692','East Newnan CDP','East Newnan CDP','CITY'),
(nextval('public.hibernate_sequence'),'1325720','East Point city','East Point city','CITY'),
(nextval('public.hibernate_sequence'),'1326084','Eatonton city','Eatonton city','CITY'),
(nextval('public.hibernate_sequence'),'1326224','Edge Hill city','Edge Hill city','CITY'),
(nextval('public.hibernate_sequence'),'1326448','Edison city','Edison city','CITY'),
(nextval('public.hibernate_sequence'),'1326616','Elberton city','Elberton city','CITY'),
(nextval('public.hibernate_sequence'),'1326980','Ellaville city','Ellaville city','CITY'),
(nextval('public.hibernate_sequence'),'1327008','Ellenton town','Ellenton town','CITY'),
(nextval('public.hibernate_sequence'),'1327092','Ellijay city','Ellijay city','CITY'),
(nextval('public.hibernate_sequence'),'1327344','Emerson city','Emerson city','CITY'),
(nextval('public.hibernate_sequence'),'1327512','Empire CDP','Empire CDP','CITY'),
(nextval('public.hibernate_sequence'),'1327596','Enigma town','Enigma town','CITY'),
(nextval('public.hibernate_sequence'),'1327708','Ephesus city','Ephesus city','CITY'),
(nextval('public.hibernate_sequence'),'1327736','Epworth CDP','Epworth CDP','CITY'),
(nextval('public.hibernate_sequence'),'1327932','Eton city','Eton city','CITY'),
(nextval('public.hibernate_sequence'),'1327988','Euharlee city','Euharlee city','CITY'),
(nextval('public.hibernate_sequence'),'1328044','Evans CDP','Evans CDP','CITY'),
(nextval('public.hibernate_sequence'),'1328296','Experiment CDP','Experiment CDP','CITY'),
(nextval('public.hibernate_sequence'),'1328380','Fairburn city','Fairburn city','CITY'),
(nextval('public.hibernate_sequence'),'1328492','Fairmount city','Fairmount city','CITY'),
(nextval('public.hibernate_sequence'),'1328520','Fair Oaks CDP','Fair Oaks CDP','CITY'),
(nextval('public.hibernate_sequence'),'1328632','Fairview CDP','Fairview CDP','CITY'),
(nextval('public.hibernate_sequence'),'1328744','Fargo city','Fargo city','CITY'),
(nextval('public.hibernate_sequence'),'1328968','Fayetteville city','Fayetteville city','CITY'),
(nextval('public.hibernate_sequence'),'1329528','Fitzgerald city','Fitzgerald city','CITY'),
(nextval('public.hibernate_sequence'),'1330088','Flemington city','Flemington city','CITY'),
(nextval('public.hibernate_sequence'),'1330312','Flovilla city','Flovilla city','CITY'),
(nextval('public.hibernate_sequence'),'1330340','Flowery Branch city','Flowery Branch city','CITY'),
(nextval('public.hibernate_sequence'),'1330424','Folkston city','Folkston city','CITY'),
(nextval('public.hibernate_sequence'),'1330536','Forest Park city','Forest Park city','CITY'),
(nextval('public.hibernate_sequence'),'1330732','Forsyth city','Forsyth city','CITY'),
(nextval('public.hibernate_sequence'),'1330816','Fort Gaines city','Fort Gaines city','CITY'),
(nextval('public.hibernate_sequence'),'1330956','Fort Oglethorpe city','Fort Oglethorpe city','CITY'),
(nextval('public.hibernate_sequence'),'1331068','Fort Stewart CDP','Fort Stewart CDP','CITY'),
(nextval('public.hibernate_sequence'),'1331096','Fort Valley city','Fort Valley city','CITY'),
(nextval('public.hibernate_sequence'),'1331292','Franklin city','Franklin city','CITY'),
(nextval('public.hibernate_sequence'),'1331320','Franklin Springs city','Franklin Springs city','CITY'),
(nextval('public.hibernate_sequence'),'1331684','Funston city','Funston city','CITY'),
(nextval('public.hibernate_sequence'),'1331908','Gainesville city','Gainesville city','CITY'),
(nextval('public.hibernate_sequence'),'1332048','Garden City city','Garden City city','CITY'),
(nextval('public.hibernate_sequence'),'1332188','Garfield city','Garfield city','CITY'),
(nextval('public.hibernate_sequence'),'1332384','Gay town','Gay town','CITY'),
(nextval('public.hibernate_sequence'),'1332412','Geneva town','Geneva town','CITY'),
(nextval('public.hibernate_sequence'),'1332482','Georgetown CDP','Georgetown CDP','CITY'),
(nextval('public.hibernate_sequence'),'1332528','Georgetown-Quitman County unified government','Georgetown-Quitman County unified government','CITY'),
(nextval('public.hibernate_sequence'),'1332748','Gibson city','Gibson city','CITY'),
(nextval('public.hibernate_sequence'),'1332860','Gillsville city','Gillsville city','CITY'),
(nextval('public.hibernate_sequence'),'1332916','Girard town','Girard town','CITY'),
(nextval('public.hibernate_sequence'),'1333336','Glennville city','Glennville city','CITY'),
(nextval('public.hibernate_sequence'),'1333392','Glenwood city','Glenwood city','CITY'),
(nextval('public.hibernate_sequence'),'1333896','Good Hope city','Good Hope city','CITY'),
(nextval('public.hibernate_sequence'),'1333980','Gordon city','Gordon city','CITY'),
(nextval('public.hibernate_sequence'),'1334260','Graham city','Graham city','CITY'),
(nextval('public.hibernate_sequence'),'1334428','Grantville city','Grantville city','CITY'),
(nextval('public.hibernate_sequence'),'1334512','Gray city','Gray city','CITY'),
(nextval('public.hibernate_sequence'),'1334596','Grayson city','Grayson city','CITY'),
(nextval('public.hibernate_sequence'),'1334876','Greensboro city','Greensboro city','CITY'),
(nextval('public.hibernate_sequence'),'1335016','Greenville city','Greenville city','CITY'),
(nextval('public.hibernate_sequence'),'1335240','Gresham Park CDP','Gresham Park CDP','CITY'),
(nextval('public.hibernate_sequence'),'1335324','Griffin city','Griffin city','CITY'),
(nextval('public.hibernate_sequence'),'1335716','Grovetown city','Grovetown city','CITY'),
(nextval('public.hibernate_sequence'),'1335800','Gumbranch city','Gumbranch city','CITY'),
(nextval('public.hibernate_sequence'),'1335814','Gumlog CDP','Gumlog CDP','CITY'),
(nextval('public.hibernate_sequence'),'1335884','Guyton city','Guyton city','CITY'),
(nextval('public.hibernate_sequence'),'1336024','Hagan city','Hagan city','CITY'),
(nextval('public.hibernate_sequence'),'1336052','Hahira city','Hahira city','CITY'),
(nextval('public.hibernate_sequence'),'1336220','Hamilton city','Hamilton city','CITY'),
(nextval('public.hibernate_sequence'),'1336276','Hampton city','Hampton city','CITY'),
(nextval('public.hibernate_sequence'),'1336416','Hannahs Mill CDP','Hannahs Mill CDP','CITY'),
(nextval('public.hibernate_sequence'),'1336472','Hapeville city','Hapeville city','CITY'),
(nextval('public.hibernate_sequence'),'1336528','Haralson town','Haralson town','CITY'),
(nextval('public.hibernate_sequence'),'1336668','Hardwick CDP','Hardwick CDP','CITY'),
(nextval('public.hibernate_sequence'),'1336696','Harlem city','Harlem city','CITY'),
(nextval('public.hibernate_sequence'),'1336920','Harrison town','Harrison town','CITY'),
(nextval('public.hibernate_sequence'),'1337144','Hartwell city','Hartwell city','CITY'),
(nextval('public.hibernate_sequence'),'1337396','Hawkinsville city','Hawkinsville city','CITY'),
(nextval('public.hibernate_sequence'),'1337564','Hazlehurst city','Hazlehurst city','CITY'),
(nextval('public.hibernate_sequence'),'1337788','Helen city','Helen city','CITY'),
(nextval('public.hibernate_sequence'),'1337816','Helena city','Helena city','CITY'),
(nextval('public.hibernate_sequence'),'1337910','Henderson CDP','Henderson CDP','CITY'),
(nextval('public.hibernate_sequence'),'1338040','Hephzibah city','Hephzibah city','CITY'),
(nextval('public.hibernate_sequence'),'1338105','Heron Bay CDP','Heron Bay CDP','CITY'),
(nextval('public.hibernate_sequence'),'1338124','Hiawassee city','Hiawassee city','CITY'),
(nextval('public.hibernate_sequence'),'1338348','Higgston town','Higgston town','CITY'),
(nextval('public.hibernate_sequence'),'1338866','Hilltop CDP','Hilltop CDP','CITY'),
(nextval('public.hibernate_sequence'),'1338920','Hiltonia town','Hiltonia town','CITY'),
(nextval('public.hibernate_sequence'),'1338964','Hinesville city','Hinesville city','CITY'),
(nextval('public.hibernate_sequence'),'1339076','Hiram city','Hiram city','CITY'),
(nextval('public.hibernate_sequence'),'1339216','Hoboken city','Hoboken city','CITY'),
(nextval('public.hibernate_sequence'),'1339244','Hogansville city','Hogansville city','CITY'),
(nextval('public.hibernate_sequence'),'1339524','Holly Springs city','Holly Springs city','CITY'),
(nextval('public.hibernate_sequence'),'1339692','Homeland city','Homeland city','CITY'),
(nextval('public.hibernate_sequence'),'1339720','Homer town','Homer town','CITY'),
(nextval('public.hibernate_sequence'),'1339748','Homerville city','Homerville city','CITY'),
(nextval('public.hibernate_sequence'),'1340056','Hoschton city','Hoschton city','CITY'),
(nextval('public.hibernate_sequence'),'1340196','Howard CDP','Howard CDP','CITY'),
(nextval('public.hibernate_sequence'),'1340532','Hull city','Hull city','CITY'),
(nextval('public.hibernate_sequence'),'1340812','Ideal city','Ideal city','CITY'),
(nextval('public.hibernate_sequence'),'1340840','Ila city','Ila city','CITY'),
(nextval('public.hibernate_sequence'),'1341036','Indian Springs CDP','Indian Springs CDP','CITY'),
(nextval('public.hibernate_sequence'),'1341344','Iron City town','Iron City town','CITY'),
(nextval('public.hibernate_sequence'),'1341347','Irondale CDP','Irondale CDP','CITY'),
(nextval('public.hibernate_sequence'),'1341400','Irwinton city','Irwinton city','CITY'),
(nextval('public.hibernate_sequence'),'1341484','Isle of Hope CDP','Isle of Hope CDP','CITY'),
(nextval('public.hibernate_sequence'),'1341540','Ivey city','Ivey city','CITY'),
(nextval('public.hibernate_sequence'),'1341596','Jackson city','Jackson city','CITY'),
(nextval('public.hibernate_sequence'),'1341708','Jacksonville city','Jacksonville city','CITY'),
(nextval('public.hibernate_sequence'),'1341792','Jakin city','Jakin city','CITY'),
(nextval('public.hibernate_sequence'),'1341932','Jasper city','Jasper city','CITY'),
(nextval('public.hibernate_sequence'),'1341988','Jefferson city','Jefferson city','CITY'),
(nextval('public.hibernate_sequence'),'1342100','Jeffersonville city','Jeffersonville city','CITY'),
(nextval('public.hibernate_sequence'),'1342156','Jenkinsburg city','Jenkinsburg city','CITY'),
(nextval('public.hibernate_sequence'),'1342184','Jersey city','Jersey city','CITY'),
(nextval('public.hibernate_sequence'),'1342268','Jesup city','Jesup city','CITY'),
(nextval('public.hibernate_sequence'),'1342425','Johns Creek city','Johns Creek city','CITY'),
(nextval('public.hibernate_sequence'),'1342604','Jonesboro city','Jonesboro city','CITY'),
(nextval('public.hibernate_sequence'),'1342800','Junction City town','Junction City town','CITY'),
(nextval('public.hibernate_sequence'),'1343192','Kennesaw city','Kennesaw city','CITY'),
(nextval('public.hibernate_sequence'),'1343360','Keysville city','Keysville city','CITY'),
(nextval('public.hibernate_sequence'),'1343580','Kings Bay Base CDP','Kings Bay Base CDP','CITY'),
(nextval('public.hibernate_sequence'),'1343640','Kingsland city','Kingsland city','CITY'),
(nextval('public.hibernate_sequence'),'1343668','Kingston city','Kingston city','CITY'),
(nextval('public.hibernate_sequence'),'1343892','Kite city','Kite city','CITY'),
(nextval('public.hibernate_sequence'),'1344060','Knoxville CDP','Knoxville CDP','CITY'),
(nextval('public.hibernate_sequence'),'1344312','LaFayette city','LaFayette city','CITY'),
(nextval('public.hibernate_sequence'),'1344340','LaGrange city','LaGrange city','CITY'),
(nextval('public.hibernate_sequence'),'1344508','Lake City city','Lake City city','CITY'),
(nextval('public.hibernate_sequence'),'1344592','Lakeland city','Lakeland city','CITY'),
(nextval('public.hibernate_sequence'),'1344704','Lake Park city','Lake Park city','CITY'),
(nextval('public.hibernate_sequence'),'1344900','Lakeview CDP','Lakeview CDP','CITY'),
(nextval('public.hibernate_sequence'),'1344956','Lakeview Estates CDP','Lakeview Estates CDP','CITY'),
(nextval('public.hibernate_sequence'),'1345460','Lavonia city','Lavonia city','CITY'),
(nextval('public.hibernate_sequence'),'1345488','Lawrenceville city','Lawrenceville city','CITY'),
(nextval('public.hibernate_sequence'),'1345600','Leary city','Leary city','CITY'),
(nextval('public.hibernate_sequence'),'1345768','Leesburg city','Leesburg city','CITY'),
(nextval('public.hibernate_sequence'),'1345936','Lenox town','Lenox town','CITY'),
(nextval('public.hibernate_sequence'),'1346020','Leslie city','Leslie city','CITY'),
(nextval('public.hibernate_sequence'),'1346188','Lexington city','Lexington city','CITY'),
(nextval('public.hibernate_sequence'),'1346356','Lilburn city','Lilburn city','CITY'),
(nextval('public.hibernate_sequence'),'1346384','Lilly city','Lilly city','CITY'),
(nextval('public.hibernate_sequence'),'1346524','Lincoln Park CDP','Lincoln Park CDP','CITY'),
(nextval('public.hibernate_sequence'),'1346552','Lincolnton city','Lincolnton city','CITY'),
(nextval('public.hibernate_sequence'),'1346580','Lindale CDP','Lindale CDP','CITY'),
(nextval('public.hibernate_sequence'),'1346832','Lithia Springs CDP','Lithia Springs CDP','CITY'),
(nextval('public.hibernate_sequence'),'1346860','Lithonia city','Lithonia city','CITY'),
(nextval('public.hibernate_sequence'),'1347140','Locust Grove city','Locust Grove city','CITY'),
(nextval('public.hibernate_sequence'),'1347196','Loganville city','Loganville city','CITY'),
(nextval('public.hibernate_sequence'),'1347252','Lone Oak town','Lone Oak town','CITY'),
(nextval('public.hibernate_sequence'),'1347336','Lookout Mountain city','Lookout Mountain city','CITY'),
(nextval('public.hibernate_sequence'),'1347560','Louisville city','Louisville city','CITY'),
(nextval('public.hibernate_sequence'),'1347616','Lovejoy city','Lovejoy city','CITY'),
(nextval('public.hibernate_sequence'),'1347784','Ludowici city','Ludowici city','CITY'),
(nextval('public.hibernate_sequence'),'1347896','Lula city','Lula city','CITY'),
(nextval('public.hibernate_sequence'),'1347952','Lumber City city','Lumber City city','CITY'),
(nextval('public.hibernate_sequence'),'1347980','Lumpkin city','Lumpkin city','CITY'),
(nextval('public.hibernate_sequence'),'1348008','Luthersville city','Luthersville city','CITY'),
(nextval('public.hibernate_sequence'),'1348092','Lyerly town','Lyerly town','CITY'),
(nextval('public.hibernate_sequence'),'1348232','Lyons city','Lyons city','CITY'),
(nextval('public.hibernate_sequence'),'1348288','Mableton CDP','Mableton CDP','CITY'),
(nextval('public.hibernate_sequence'),'1348428','McCaysville city','McCaysville city','CITY'),
(nextval('public.hibernate_sequence'),'1348624','McDonough city','McDonough city','CITY'),
(nextval('public.hibernate_sequence'),'1348848','McIntyre town','McIntyre town','CITY'),
(nextval('public.hibernate_sequence'),'1349000','Macon city','Macon city','CITY'),
(nextval('public.hibernate_sequence'),'1349084','McRae city','McRae city','CITY'),
(nextval('public.hibernate_sequence'),'1349196','Madison city','Madison city','CITY'),
(nextval('public.hibernate_sequence'),'1349504','Manassas city','Manassas city','CITY'),
(nextval('public.hibernate_sequence'),'1349532','Manchester city','Manchester city','CITY'),
(nextval('public.hibernate_sequence'),'1349616','Mansfield city','Mansfield city','CITY'),
(nextval('public.hibernate_sequence'),'1349756','Marietta city','Marietta city','CITY'),
(nextval('public.hibernate_sequence'),'1349924','Marshallville city','Marshallville city','CITY'),
(nextval('public.hibernate_sequence'),'1350008','Martin town','Martin town','CITY'),
(nextval('public.hibernate_sequence'),'1350036','Martinez CDP','Martinez CDP','CITY'),
(nextval('public.hibernate_sequence'),'1350176','Matthews CDP','Matthews CDP','CITY'),
(nextval('public.hibernate_sequence'),'1350260','Maxeys town','Maxeys town','CITY'),
(nextval('public.hibernate_sequence'),'1350484','Maysville town','Maysville town','CITY'),
(nextval('public.hibernate_sequence'),'1350596','Meansville city','Meansville city','CITY'),
(nextval('public.hibernate_sequence'),'1350680','Meigs city','Meigs city','CITY'),
(nextval('public.hibernate_sequence'),'1350820','Mendes CDP','Mendes CDP','CITY'),
(nextval('public.hibernate_sequence'),'1350848','Menlo city','Menlo city','CITY'),
(nextval('public.hibernate_sequence'),'1351072','Metter city','Metter city','CITY'),
(nextval('public.hibernate_sequence'),'1351240','Midville city','Midville city','CITY'),
(nextval('public.hibernate_sequence'),'1351352','Midway city','Midway city','CITY'),
(nextval('public.hibernate_sequence'),'1351408','Milan city','Milan city','CITY'),
(nextval('public.hibernate_sequence'),'1351492','Milledgeville city','Milledgeville city','CITY'),
(nextval('public.hibernate_sequence'),'1351520','Millen city','Millen city','CITY'),
(nextval('public.hibernate_sequence'),'1351604','Milner city','Milner city','CITY'),
(nextval('public.hibernate_sequence'),'1351670','Milton city','Milton city','CITY'),
(nextval('public.hibernate_sequence'),'1351744','Mineral Bluff CDP','Mineral Bluff CDP','CITY'),
(nextval('public.hibernate_sequence'),'1351968','Mitchell town','Mitchell town','CITY'),
(nextval('public.hibernate_sequence'),'1352108','Molena city','Molena city','CITY'),
(nextval('public.hibernate_sequence'),'1352192','Monroe city','Monroe city','CITY'),
(nextval('public.hibernate_sequence'),'1352304','Montezuma city','Montezuma city','CITY'),
(nextval('public.hibernate_sequence'),'1352332','Montgomery CDP','Montgomery CDP','CITY'),
(nextval('public.hibernate_sequence'),'1352416','Monticello city','Monticello city','CITY'),
(nextval('public.hibernate_sequence'),'1352500','Montrose town','Montrose town','CITY'),
(nextval('public.hibernate_sequence'),'1352556','Moody AFB CDP','Moody AFB CDP','CITY'),
(nextval('public.hibernate_sequence'),'1352668','Moreland town','Moreland town','CITY'),
(nextval('public.hibernate_sequence'),'1352696','Morgan city','Morgan city','CITY'),
(nextval('public.hibernate_sequence'),'1352724','Morganton city','Morganton city','CITY'),
(nextval('public.hibernate_sequence'),'1353004','Morrow city','Morrow city','CITY'),
(nextval('public.hibernate_sequence'),'1353032','Morven city','Morven city','CITY'),
(nextval('public.hibernate_sequence'),'1353060','Moultrie city','Moultrie city','CITY'),
(nextval('public.hibernate_sequence'),'1353116','Mountain City town','Mountain City town','CITY'),
(nextval('public.hibernate_sequence'),'1353172','Mountain Park city','Mountain Park city','CITY'),
(nextval('public.hibernate_sequence'),'1353186','Mountain Park CDP','Mountain Park CDP','CITY'),
(nextval('public.hibernate_sequence'),'1353284','Mount Airy town','Mount Airy town','CITY'),
(nextval('public.hibernate_sequence'),'1353508','Mount Vernon city','Mount Vernon city','CITY'),
(nextval('public.hibernate_sequence'),'1353620','Mount Zion city','Mount Zion city','CITY'),
(nextval('public.hibernate_sequence'),'1354124','Nahunta city','Nahunta city','CITY'),
(nextval('public.hibernate_sequence'),'1354264','Nashville city','Nashville city','CITY'),
(nextval('public.hibernate_sequence'),'1354572','Nelson city','Nelson city','CITY'),
(nextval('public.hibernate_sequence'),'1354656','Newborn town','Newborn town','CITY'),
(nextval('public.hibernate_sequence'),'1354992','Newington town','Newington town','CITY'),
(nextval('public.hibernate_sequence'),'1355020','Newnan city','Newnan city','CITY'),
(nextval('public.hibernate_sequence'),'1355244','Newton city','Newton city','CITY'),
(nextval('public.hibernate_sequence'),'1355440','Nicholls city','Nicholls city','CITY'),
(nextval('public.hibernate_sequence'),'1355468','Nicholson city','Nicholson city','CITY'),
(nextval('public.hibernate_sequence'),'1355776','Norcross city','Norcross city','CITY'),
(nextval('public.hibernate_sequence'),'1355860','Norman Park city','Norman Park city','CITY'),
(nextval('public.hibernate_sequence'),'1355944','Norristown CDP','Norristown CDP','CITY'),
(nextval('public.hibernate_sequence'),'1356000','North Atlanta CDP','North Atlanta CDP','CITY'),
(nextval('public.hibernate_sequence'),'1356112','North Decatur CDP','North Decatur CDP','CITY'),
(nextval('public.hibernate_sequence'),'1356168','North Druid Hills CDP','North Druid Hills CDP','CITY'),
(nextval('public.hibernate_sequence'),'1356308','North High Shoals town','North High Shoals town','CITY'),
(nextval('public.hibernate_sequence'),'1356560','Norwood city','Norwood city','CITY'),
(nextval('public.hibernate_sequence'),'1356644','Nunez city','Nunez city','CITY'),
(nextval('public.hibernate_sequence'),'1357232','Oak Park town','Oak Park town','CITY'),
(nextval('public.hibernate_sequence'),'1357260','Oakwood city','Oakwood city','CITY'),
(nextval('public.hibernate_sequence'),'1357372','Ochlocknee town','Ochlocknee town','CITY'),
(nextval('public.hibernate_sequence'),'1357428','Ocilla city','Ocilla city','CITY'),
(nextval('public.hibernate_sequence'),'1357456','Oconee city','Oconee city','CITY'),
(nextval('public.hibernate_sequence'),'1357540','Odum city','Odum city','CITY'),
(nextval('public.hibernate_sequence'),'1357568','Offerman city','Offerman city','CITY'),
(nextval('public.hibernate_sequence'),'1357736','Oglethorpe city','Oglethorpe city','CITY'),
(nextval('public.hibernate_sequence'),'1358100','Oliver city','Oliver city','CITY'),
(nextval('public.hibernate_sequence'),'1358184','Omega city','Omega city','CITY'),
(nextval('public.hibernate_sequence'),'1358296','Orchard Hill town','Orchard Hill town','CITY'),
(nextval('public.hibernate_sequence'),'1358744','Oxford city','Oxford city','CITY'),
(nextval('public.hibernate_sequence'),'1358884','Palmetto city','Palmetto city','CITY'),
(nextval('public.hibernate_sequence'),'1359080','Panthersville CDP','Panthersville CDP','CITY'),
(nextval('public.hibernate_sequence'),'1359416','Parrott town','Parrott town','CITY'),
(nextval('public.hibernate_sequence'),'1359500','Patterson city','Patterson city','CITY'),
(nextval('public.hibernate_sequence'),'1359556','Pavo city','Pavo city','CITY'),
(nextval('public.hibernate_sequence'),'1359584','Payne city','Payne city','CITY'),
(nextval('public.hibernate_sequence'),'1359724','Peachtree City city','Peachtree City city','CITY'),
(nextval('public.hibernate_sequence'),'1359808','Pearson city','Pearson city','CITY'),
(nextval('public.hibernate_sequence'),'1359976','Pelham city','Pelham city','CITY'),
(nextval('public.hibernate_sequence'),'1360004','Pembroke city','Pembroke city','CITY'),
(nextval('public.hibernate_sequence'),'1360032','Pendergrass town','Pendergrass town','CITY'),
(nextval('public.hibernate_sequence'),'1360312','Perkins CDP','Perkins CDP','CITY'),
(nextval('public.hibernate_sequence'),'1360340','Perry city','Perry city','CITY'),
(nextval('public.hibernate_sequence'),'1360508','Phillipsburg CDP','Phillipsburg CDP','CITY'),
(nextval('public.hibernate_sequence'),'1360984','Pinehurst city','Pinehurst city','CITY'),
(nextval('public.hibernate_sequence'),'1361040','Pine Lake city','Pine Lake city','CITY'),
(nextval('public.hibernate_sequence'),'1361124','Pine Mountain town','Pine Mountain town','CITY'),
(nextval('public.hibernate_sequence'),'1361320','Pineview town','Pineview town','CITY'),
(nextval('public.hibernate_sequence'),'1361544','Pitts city','Pitts city','CITY'),
(nextval('public.hibernate_sequence'),'1361628','Plains city','Plains city','CITY'),
(nextval('public.hibernate_sequence'),'1361684','Plainville city','Plainville city','CITY'),
(nextval('public.hibernate_sequence'),'1362104','Pooler city','Pooler city','CITY'),
(nextval('public.hibernate_sequence'),'1362216','Portal town','Portal town','CITY'),
(nextval('public.hibernate_sequence'),'1362244','Porterdale city','Porterdale city','CITY'),
(nextval('public.hibernate_sequence'),'1362328','Port Wentworth city','Port Wentworth city','CITY'),
(nextval('public.hibernate_sequence'),'1362496','Poulan city','Poulan city','CITY'),
(nextval('public.hibernate_sequence'),'1362524','Powder Springs city','Powder Springs city','CITY'),
(nextval('public.hibernate_sequence'),'1363000','Pulaski town','Pulaski town','CITY'),
(nextval('public.hibernate_sequence'),'1363084','Putney CDP','Putney CDP','CITY'),
(nextval('public.hibernate_sequence'),'1363224','Quitman city','Quitman city','CITY'),
(nextval('public.hibernate_sequence'),'1363560','Ranger town','Ranger town','CITY'),
(nextval('public.hibernate_sequence'),'1363588','Raoul CDP','Raoul CDP','CITY'),
(nextval('public.hibernate_sequence'),'1363728','Ray City city','Ray City city','CITY'),
(nextval('public.hibernate_sequence'),'1363756','Rayle town','Rayle town','CITY'),
(nextval('public.hibernate_sequence'),'1363840','Rebecca town','Rebecca town','CITY'),
(nextval('public.hibernate_sequence'),'1363952','Redan CDP','Redan CDP','CITY'),
(nextval('public.hibernate_sequence'),'1364288','Reed Creek CDP','Reed Creek CDP','CITY'),
(nextval('public.hibernate_sequence'),'1364372','Register town','Register town','CITY'),
(nextval('public.hibernate_sequence'),'1364512','Reidsville city','Reidsville city','CITY'),
(nextval('public.hibernate_sequence'),'1364596','Remerton city','Remerton city','CITY'),
(nextval('public.hibernate_sequence'),'1364680','Rentz city','Rentz city','CITY'),
(nextval('public.hibernate_sequence'),'1364736','Resaca town','Resaca town','CITY'),
(nextval('public.hibernate_sequence'),'1364792','Rest Haven town','Rest Haven town','CITY'),
(nextval('public.hibernate_sequence'),'1364876','Reynolds city','Reynolds city','CITY'),
(nextval('public.hibernate_sequence'),'1364932','Rhine town','Rhine town','CITY'),
(nextval('public.hibernate_sequence'),'1364960','Riceboro city','Riceboro city','CITY'),
(nextval('public.hibernate_sequence'),'1365016','Richland city','Richland city','CITY'),
(nextval('public.hibernate_sequence'),'1365044','Richmond Hill city','Richmond Hill city','CITY'),
(nextval('public.hibernate_sequence'),'1365156','Riddleville town','Riddleville town','CITY'),
(nextval('public.hibernate_sequence'),'1365296','Rincon town','Rincon town','CITY'),
(nextval('public.hibernate_sequence'),'1365324','Ringgold city','Ringgold city','CITY'),
(nextval('public.hibernate_sequence'),'1365464','Riverdale city','Riverdale city','CITY'),
(nextval('public.hibernate_sequence'),'1365604','Riverside town','Riverside town','CITY'),
(nextval('public.hibernate_sequence'),'1365856','Roberta city','Roberta city','CITY'),
(nextval('public.hibernate_sequence'),'1365968','Robins AFB CDP','Robins AFB CDP','CITY'),
(nextval('public.hibernate_sequence'),'1366024','Rochelle city','Rochelle city','CITY'),
(nextval('public.hibernate_sequence'),'1366220','Rockingham CDP','Rockingham CDP','CITY'),
(nextval('public.hibernate_sequence'),'1366276','Rockmart city','Rockmart city','CITY'),
(nextval('public.hibernate_sequence'),'1366444','Rocky Ford town','Rocky Ford town','CITY'),
(nextval('public.hibernate_sequence'),'1366668','Rome city','Rome city','CITY'),
(nextval('public.hibernate_sequence'),'1366696','Roopville town','Roopville town','CITY'),
(nextval('public.hibernate_sequence'),'1367256','Rossville city','Rossville city','CITY'),
(nextval('public.hibernate_sequence'),'1367284','Roswell city','Roswell city','CITY'),
(nextval('public.hibernate_sequence'),'1367452','Royston city','Royston city','CITY'),
(nextval('public.hibernate_sequence'),'1367676','Russell CDP','Russell CDP','CITY'),
(nextval('public.hibernate_sequence'),'1367760','Rutledge city','Rutledge city','CITY'),
(nextval('public.hibernate_sequence'),'1367984','St. Marys city','St. Marys city','CITY'),
(nextval('public.hibernate_sequence'),'1368040','St. Simons CDP','St. Simons CDP','CITY'),
(nextval('public.hibernate_sequence'),'1368096','Sale City city','Sale City city','CITY'),
(nextval('public.hibernate_sequence'),'1368129','Salem CDP','Salem CDP','CITY'),
(nextval('public.hibernate_sequence'),'1368208','Sandersville city','Sandersville city','CITY'),
(nextval('public.hibernate_sequence'),'1368516','Sandy Springs city','Sandy Springs city','CITY'),
(nextval('public.hibernate_sequence'),'1368600','Santa Claus city','Santa Claus city','CITY'),
(nextval('public.hibernate_sequence'),'1368740','Sardis city','Sardis city','CITY'),
(nextval('public.hibernate_sequence'),'1368796','Sasser town','Sasser town','CITY'),
(nextval('public.hibernate_sequence'),'1368805','Satilla CDP','Satilla CDP','CITY'),
(nextval('public.hibernate_sequence'),'1368880','Sautee Nacoochee CDP','Sautee Nacoochee CDP','CITY'),
(nextval('public.hibernate_sequence'),'1369000','Savannah city','Savannah city','CITY'),
(nextval('public.hibernate_sequence'),'1369336','Scotland city','Scotland city','CITY'),
(nextval('public.hibernate_sequence'),'1369392','Scottdale CDP','Scottdale CDP','CITY'),
(nextval('public.hibernate_sequence'),'1369448','Screven city','Screven city','CITY'),
(nextval('public.hibernate_sequence'),'1369672','Senoia city','Senoia city','CITY'),
(nextval('public.hibernate_sequence'),'1369728','Seville CDP','Seville CDP','CITY'),
(nextval('public.hibernate_sequence'),'1369784','Shady Dale town','Shady Dale town','CITY'),
(nextval('public.hibernate_sequence'),'1369868','Shannon CDP','Shannon CDP','CITY'),
(nextval('public.hibernate_sequence'),'1369896','Sharon city','Sharon city','CITY'),
(nextval('public.hibernate_sequence'),'1369980','Sharpsburg town','Sharpsburg town','CITY'),
(nextval('public.hibernate_sequence'),'1370120','Shellman city','Shellman city','CITY'),
(nextval('public.hibernate_sequence'),'1370428','Shiloh city','Shiloh city','CITY'),
(nextval('public.hibernate_sequence'),'1370932','Siloam town','Siloam town','CITY'),
(nextval('public.hibernate_sequence'),'1371184','Skidaway Island CDP','Skidaway Island CDP','CITY'),
(nextval('public.hibernate_sequence'),'1371282','Sky Valley city','Sky Valley city','CITY'),
(nextval('public.hibernate_sequence'),'1371464','Smithville city','Smithville city','CITY'),
(nextval('public.hibernate_sequence'),'1371492','Smyrna city','Smyrna city','CITY'),
(nextval('public.hibernate_sequence'),'1371604','Snellville city','Snellville city','CITY'),
(nextval('public.hibernate_sequence'),'1371660','Social Circle city','Social Circle city','CITY'),
(nextval('public.hibernate_sequence'),'1371772','Soperton city','Soperton city','CITY'),
(nextval('public.hibernate_sequence'),'1372556','Sparks town','Sparks town','CITY'),
(nextval('public.hibernate_sequence'),'1372584','Sparta city','Sparta city','CITY'),
(nextval('public.hibernate_sequence'),'1372780','Springfield city','Springfield city','CITY'),
(nextval('public.hibernate_sequence'),'1373004','Stapleton city','Stapleton city','CITY'),
(nextval('public.hibernate_sequence'),'1373200','Statenville CDP','Statenville CDP','CITY'),
(nextval('public.hibernate_sequence'),'1373256','Statesboro city','Statesboro city','CITY'),
(nextval('public.hibernate_sequence'),'1373312','Statham city','Statham city','CITY'),
(nextval('public.hibernate_sequence'),'1373620','Stillmore city','Stillmore city','CITY'),
(nextval('public.hibernate_sequence'),'1373704','Stockbridge city','Stockbridge city','CITY'),
(nextval('public.hibernate_sequence'),'1373816','Stone Mountain city','Stone Mountain city','CITY'),
(nextval('public.hibernate_sequence'),'1374180','Sugar Hill city','Sugar Hill city','CITY'),
(nextval('public.hibernate_sequence'),'1374348','Summertown city','Summertown city','CITY'),
(nextval('public.hibernate_sequence'),'1374376','Summerville city','Summerville city','CITY'),
(nextval('public.hibernate_sequence'),'1374432','Sumner town','Sumner town','CITY'),
(nextval('public.hibernate_sequence'),'1374572','Sunny Side city','Sunny Side city','CITY'),
(nextval('public.hibernate_sequence'),'1374628','Sunnyside CDP','Sunnyside CDP','CITY'),
(nextval('public.hibernate_sequence'),'1374768','Sunset Village CDP','Sunset Village CDP','CITY'),
(nextval('public.hibernate_sequence'),'1374852','Surrency town','Surrency town','CITY'),
(nextval('public.hibernate_sequence'),'1374936','Suwanee city','Suwanee city','CITY'),
(nextval('public.hibernate_sequence'),'1374964','Swainsboro city','Swainsboro city','CITY'),
(nextval('public.hibernate_sequence'),'1375104','Sycamore city','Sycamore city','CITY'),
(nextval('public.hibernate_sequence'),'1375160','Sylvania city','Sylvania city','CITY'),
(nextval('public.hibernate_sequence'),'1375188','Sylvester city','Sylvester city','CITY'),
(nextval('public.hibernate_sequence'),'1375239','Talahi Island CDP','Talahi Island CDP','CITY'),
(nextval('public.hibernate_sequence'),'1375244','Talbotton city','Talbotton city','CITY'),
(nextval('public.hibernate_sequence'),'1375272','Talking Rock town','Talking Rock town','CITY'),
(nextval('public.hibernate_sequence'),'1375300','Tallapoosa city','Tallapoosa city','CITY'),
(nextval('public.hibernate_sequence'),'1375328','Tallulah Falls town','Tallulah Falls town','CITY'),
(nextval('public.hibernate_sequence'),'1375412','Talmo town','Talmo town','CITY'),
(nextval('public.hibernate_sequence'),'1375496','Tarrytown town','Tarrytown town','CITY'),
(nextval('public.hibernate_sequence'),'1375580','Tate City CDP','Tate City CDP','CITY'),
(nextval('public.hibernate_sequence'),'1375664','Taylorsville town','Taylorsville town','CITY'),
(nextval('public.hibernate_sequence'),'1375832','Temple city','Temple city','CITY'),
(nextval('public.hibernate_sequence'),'1375888','Tennille city','Tennille city','CITY'),
(nextval('public.hibernate_sequence'),'1376112','The Rock CDP','The Rock CDP','CITY'),
(nextval('public.hibernate_sequence'),'1376168','Thomaston city','Thomaston city','CITY'),
(nextval('public.hibernate_sequence'),'1376224','Thomasville city','Thomasville city','CITY'),
(nextval('public.hibernate_sequence'),'1376280','Thomson city','Thomson city','CITY'),
(nextval('public.hibernate_sequence'),'1376364','Thunderbolt town','Thunderbolt town','CITY'),
(nextval('public.hibernate_sequence'),'1376476','Tifton city','Tifton city','CITY'),
(nextval('public.hibernate_sequence'),'1376504','Tiger town','Tiger town','CITY'),
(nextval('public.hibernate_sequence'),'1376532','Tignall town','Tignall town','CITY'),
(nextval('public.hibernate_sequence'),'1376756','Toccoa city','Toccoa city','CITY'),
(nextval('public.hibernate_sequence'),'1376952','Toomsboro city','Toomsboro city','CITY'),
(nextval('public.hibernate_sequence'),'1377372','Trenton city','Trenton city','CITY'),
(nextval('public.hibernate_sequence'),'1377540','Trion town','Trion town','CITY'),
(nextval('public.hibernate_sequence'),'1377652','Tucker CDP','Tucker CDP','CITY'),
(nextval('public.hibernate_sequence'),'1377736','Tunnel Hill city','Tunnel Hill city','CITY'),
(nextval('public.hibernate_sequence'),'1377764','Turin town','Turin town','CITY'),
(nextval('public.hibernate_sequence'),'1377988','Twin City city','Twin City city','CITY'),
(nextval('public.hibernate_sequence'),'1378036','Tybee Island city','Tybee Island city','CITY'),
(nextval('public.hibernate_sequence'),'1378044','Tyrone town','Tyrone town','CITY'),
(nextval('public.hibernate_sequence'),'1378100','Ty Ty city','Ty Ty city','CITY'),
(nextval('public.hibernate_sequence'),'1378156','Unadilla city','Unadilla city','CITY'),
(nextval('public.hibernate_sequence'),'1378324','Union City city','Union City city','CITY'),
(nextval('public.hibernate_sequence'),'1378380','Union Point city','Union Point city','CITY'),
(nextval('public.hibernate_sequence'),'1378464','Unionville CDP','Unionville CDP','CITY'),
(nextval('public.hibernate_sequence'),'1378744','Uvalda city','Uvalda city','CITY'),
(nextval('public.hibernate_sequence'),'1378800','Valdosta city','Valdosta city','CITY'),
(nextval('public.hibernate_sequence'),'1378996','Varnell city','Varnell city','CITY'),
(nextval('public.hibernate_sequence'),'1379164','Vernonburg town','Vernonburg town','CITY'),
(nextval('public.hibernate_sequence'),'1379388','Vidalia city','Vidalia city','CITY'),
(nextval('public.hibernate_sequence'),'1379416','Vidette city','Vidette city','CITY'),
(nextval('public.hibernate_sequence'),'1379444','Vienna city','Vienna city','CITY'),
(nextval('public.hibernate_sequence'),'1379528','Villa Rica city','Villa Rica city','CITY'),
(nextval('public.hibernate_sequence'),'1379612','Vinings CDP','Vinings CDP','CITY'),
(nextval('public.hibernate_sequence'),'1379808','Waco city','Waco city','CITY'),
(nextval('public.hibernate_sequence'),'1379864','Wadley city','Wadley city','CITY'),
(nextval('public.hibernate_sequence'),'1379948','Waleska city','Waleska city','CITY'),
(nextval('public.hibernate_sequence'),'1380228','Walnut Grove city','Walnut Grove city','CITY'),
(nextval('public.hibernate_sequence'),'1380256','Walthourville city','Walthourville city','CITY'),
(nextval('public.hibernate_sequence'),'1380480','Warm Springs city','Warm Springs city','CITY'),
(nextval('public.hibernate_sequence'),'1380508','Warner Robins city','Warner Robins city','CITY'),
(nextval('public.hibernate_sequence'),'1380592','Warrenton city','Warrenton city','CITY'),
(nextval('public.hibernate_sequence'),'1380676','Warwick city','Warwick city','CITY'),
(nextval('public.hibernate_sequence'),'1380704','Washington city','Washington city','CITY'),
(nextval('public.hibernate_sequence'),'1380788','Watkinsville city','Watkinsville city','CITY'),
(nextval('public.hibernate_sequence'),'1380844','Waverly Hall town','Waverly Hall town','CITY'),
(nextval('public.hibernate_sequence'),'1380956','Waycross city','Waycross city','CITY'),
(nextval('public.hibernate_sequence'),'1380984','Waynesboro city','Waynesboro city','CITY'),
(nextval('public.hibernate_sequence'),'1381128','Webster County unified government','Webster County unified government','CITY'),
(nextval('public.hibernate_sequence'),'1382132','West Point city','West Point city','CITY'),
(nextval('public.hibernate_sequence'),'1382412','Whigham city','Whigham city','CITY'),
(nextval('public.hibernate_sequence'),'1382468','White city','White city','CITY'),
(nextval('public.hibernate_sequence'),'1382636','Whitemarsh Island CDP','Whitemarsh Island CDP','CITY'),
(nextval('public.hibernate_sequence'),'1382692','White Plains city','White Plains city','CITY'),
(nextval('public.hibernate_sequence'),'1382720','Whitesburg city','Whitesburg city','CITY'),
(nextval('public.hibernate_sequence'),'1382972','Willacoochee city','Willacoochee city','CITY'),
(nextval('public.hibernate_sequence'),'1383084','Williamson city','Williamson city','CITY'),
(nextval('public.hibernate_sequence'),'1383168','Wilmington Island CDP','Wilmington Island CDP','CITY'),
(nextval('public.hibernate_sequence'),'1383420','Winder city','Winder city','CITY'),
(nextval('public.hibernate_sequence'),'1383728','Winterville city','Winterville city','CITY'),
(nextval('public.hibernate_sequence'),'1383868','Woodbine city','Woodbine city','CITY'),
(nextval('public.hibernate_sequence'),'1383896','Woodbury city','Woodbury city','CITY'),
(nextval('public.hibernate_sequence'),'1383952','Woodland city','Woodland city','CITY'),
(nextval('public.hibernate_sequence'),'1384176','Woodstock city','Woodstock city','CITY'),
(nextval('public.hibernate_sequence'),'1384260','Woodville city','Woodville city','CITY'),
(nextval('public.hibernate_sequence'),'1384288','Woolsey town','Woolsey town','CITY'),
(nextval('public.hibernate_sequence'),'1384456','Wrens city','Wrens city','CITY'),
(nextval('public.hibernate_sequence'),'1384512','Wrightsville city','Wrightsville city','CITY'),
(nextval('public.hibernate_sequence'),'1384708','Yatesville town','Yatesville town','CITY'),
(nextval('public.hibernate_sequence'),'1384832','Yonah CDP','Yonah CDP','CITY'),
(nextval('public.hibernate_sequence'),'1384960','Young Harris city','Young Harris city','CITY'),
(nextval('public.hibernate_sequence'),'1385128','Zebulon city','Zebulon city','CITY')
;
