INSERT INTO public.tax_rate(
            id, tax_definition_key, rate, range_low, range_high)
    VALUES
(nextval('public.hibernate_sequence'),'APPLING_GA_COUNTY_PROPERTY',0.0075,null,null),
(nextval('public.hibernate_sequence'),'ATKINSON_GA_COUNTY_PROPERTY',0.0068,null,null),
(nextval('public.hibernate_sequence'),'BACON_GA_COUNTY_PROPERTY',0.0079,null,null),
(nextval('public.hibernate_sequence'),'BAKER_GA_COUNTY_PROPERTY',0.0089,null,null),
(nextval('public.hibernate_sequence'),'BALDWIN_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'BANKS_GA_COUNTY_PROPERTY',0.0071,null,null),
(nextval('public.hibernate_sequence'),'BARROW_GA_COUNTY_PROPERTY',0.0094,null,null),
(nextval('public.hibernate_sequence'),'BARTOW_GA_COUNTY_PROPERTY',0.0074,null,null),
(nextval('public.hibernate_sequence'),'BEN_HILL_GA_COUNTY_PROPERTY',0.0087,null,null),
(nextval('public.hibernate_sequence'),'BERRIEN_GA_COUNTY_PROPERTY',0.0102,null,null),
(nextval('public.hibernate_sequence'),'BIBB_GA_COUNTY_PROPERTY',0.0107,null,null),
(nextval('public.hibernate_sequence'),'BLECKLEY_GA_COUNTY_PROPERTY',0.0118,null,null),
(nextval('public.hibernate_sequence'),'BRANTLEY_GA_COUNTY_PROPERTY',0.0113,null,null),
(nextval('public.hibernate_sequence'),'BROOKS_GA_COUNTY_PROPERTY',0.0103,null,null),
(nextval('public.hibernate_sequence'),'BRYAN_GA_COUNTY_PROPERTY',0.0085,null,null),
(nextval('public.hibernate_sequence'),'BULLOCH_GA_COUNTY_PROPERTY',0.0084,null,null),
(nextval('public.hibernate_sequence'),'BURKE_GA_COUNTY_PROPERTY',0.0080,null,null),
(nextval('public.hibernate_sequence'),'BUTTS_GA_COUNTY_PROPERTY',0.0119,null,null),
(nextval('public.hibernate_sequence'),'CALHOUN_GA_COUNTY_PROPERTY',0.0111,null,null),
(nextval('public.hibernate_sequence'),'CAMDEN_GA_COUNTY_PROPERTY',0.0091,null,null),
(nextval('public.hibernate_sequence'),'CANDLER_GA_COUNTY_PROPERTY',0.0107,null,null),
(nextval('public.hibernate_sequence'),'CARROLL_GA_COUNTY_PROPERTY',0.0086,null,null),
(nextval('public.hibernate_sequence'),'CATOOSA_GA_COUNTY_PROPERTY',0.0077,null,null),
(nextval('public.hibernate_sequence'),'CHARLTON_GA_COUNTY_PROPERTY',0.0115,null,null),
(nextval('public.hibernate_sequence'),'CHATHAM_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'CHATTAHOOCHEE_GA_COUNTY_PROPERTY',0.0059,null,null),
(nextval('public.hibernate_sequence'),'CHATTOOGA_GA_COUNTY_PROPERTY',0.0078,null,null),
(nextval('public.hibernate_sequence'),'CHEROKEE_GA_COUNTY_PROPERTY',0.0087,null,null),
(nextval('public.hibernate_sequence'),'CLARKE_GA_COUNTY_PROPERTY',0.0105,null,null),
(nextval('public.hibernate_sequence'),'CLAY_GA_COUNTY_PROPERTY',0.0112,null,null),
(nextval('public.hibernate_sequence'),'CLAYTON_GA_COUNTY_PROPERTY',0.0116,null,null),
(nextval('public.hibernate_sequence'),'CLINCH_GA_COUNTY_PROPERTY',0.0108,null,null),
(nextval('public.hibernate_sequence'),'COBB_GA_COUNTY_PROPERTY',0.0086,null,null),
(nextval('public.hibernate_sequence'),'COFFEE_GA_COUNTY_PROPERTY',0.0087,null,null),
(nextval('public.hibernate_sequence'),'COLQUITT_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'COLUMBIA_GA_COUNTY_PROPERTY',0.0099,null,null),
(nextval('public.hibernate_sequence'),'COOK_GA_COUNTY_PROPERTY',0.0084,null,null),
(nextval('public.hibernate_sequence'),'COWETA_GA_COUNTY_PROPERTY',0.0091,null,null),
(nextval('public.hibernate_sequence'),'CRAWFORD_GA_COUNTY_PROPERTY',0.0104,null,null),
(nextval('public.hibernate_sequence'),'CRISP_GA_COUNTY_PROPERTY',0.0092,null,null),
(nextval('public.hibernate_sequence'),'DADE_GA_COUNTY_PROPERTY',0.0059,null,null),
(nextval('public.hibernate_sequence'),'DAWSON_GA_COUNTY_PROPERTY',0.0097,null,null),
(nextval('public.hibernate_sequence'),'DECATUR_GA_COUNTY_PROPERTY',0.0078,null,null),
(nextval('public.hibernate_sequence'),'DEKALB_GA_COUNTY_PROPERTY',0.0117,null,null),
(nextval('public.hibernate_sequence'),'DODGE_GA_COUNTY_PROPERTY',0.0086,null,null),
(nextval('public.hibernate_sequence'),'DOOLY_GA_COUNTY_PROPERTY',0.0103,null,null),
(nextval('public.hibernate_sequence'),'DOUGHERTY_GA_COUNTY_PROPERTY',0.0129,null,null),
(nextval('public.hibernate_sequence'),'DOUGLAS_GA_COUNTY_PROPERTY',0.0102,null,null),
(nextval('public.hibernate_sequence'),'EARLY_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'ECHOLS_GA_COUNTY_PROPERTY',0.0101,null,null),
(nextval('public.hibernate_sequence'),'EFFINGHAM_GA_COUNTY_PROPERTY',0.0112,null,null),
(nextval('public.hibernate_sequence'),'ELBERT_GA_COUNTY_PROPERTY',0.0091,null,null),
(nextval('public.hibernate_sequence'),'EMANUEL_GA_COUNTY_PROPERTY',0.0106,null,null),
(nextval('public.hibernate_sequence'),'EVANS_GA_COUNTY_PROPERTY',0.0098,null,null),
(nextval('public.hibernate_sequence'),'FANNIN_GA_COUNTY_PROPERTY',0.0044,null,null),
(nextval('public.hibernate_sequence'),'FAYETTE_GA_COUNTY_PROPERTY',0.0110,null,null),
(nextval('public.hibernate_sequence'),'FLOYD_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'FORSYTH_GA_COUNTY_PROPERTY',0.0083,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_GA_COUNTY_PROPERTY',0.0078,null,null),
(nextval('public.hibernate_sequence'),'FULTON_GA_COUNTY_PROPERTY',0.0116,null,null),
(nextval('public.hibernate_sequence'),'GILMER_GA_COUNTY_PROPERTY',0.0058,null,null),
(nextval('public.hibernate_sequence'),'GLASCOCK_GA_COUNTY_PROPERTY',0.0104,null,null),
(nextval('public.hibernate_sequence'),'GLYNN_GA_COUNTY_PROPERTY',0.0067,null,null),
(nextval('public.hibernate_sequence'),'GORDON_GA_COUNTY_PROPERTY',0.0078,null,null),
(nextval('public.hibernate_sequence'),'GRADY_GA_COUNTY_PROPERTY',0.0083,null,null),
(nextval('public.hibernate_sequence'),'GREENE_GA_COUNTY_PROPERTY',0.0070,null,null),
(nextval('public.hibernate_sequence'),'GWINNETT_GA_COUNTY_PROPERTY',0.0127,null,null),
(nextval('public.hibernate_sequence'),'HABERSHAM_GA_COUNTY_PROPERTY',0.0074,null,null),
(nextval('public.hibernate_sequence'),'HALL_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'HANCOCK_GA_COUNTY_PROPERTY',0.0122,null,null),
(nextval('public.hibernate_sequence'),'HARALSON_GA_COUNTY_PROPERTY',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HARRIS_GA_COUNTY_PROPERTY',0.0083,null,null),
(nextval('public.hibernate_sequence'),'HART_GA_COUNTY_PROPERTY',0.0067,null,null),
(nextval('public.hibernate_sequence'),'HEARD_GA_COUNTY_PROPERTY',0.0063,null,null),
(nextval('public.hibernate_sequence'),'HENRY_GA_COUNTY_PROPERTY',0.0117,null,null),
(nextval('public.hibernate_sequence'),'HOUSTON_GA_COUNTY_PROPERTY',0.0096,null,null),
(nextval('public.hibernate_sequence'),'IRWIN_GA_COUNTY_PROPERTY',0.0101,null,null),
(nextval('public.hibernate_sequence'),'JACKSON_GA_COUNTY_PROPERTY',0.0108,null,null),
(nextval('public.hibernate_sequence'),'JASPER_GA_COUNTY_PROPERTY',0.0106,null,null),
(nextval('public.hibernate_sequence'),'JEFF_DAVIS_GA_COUNTY_PROPERTY',0.0082,null,null),
(nextval('public.hibernate_sequence'),'JEFFERSON_GA_COUNTY_PROPERTY',0.0117,null,null),
(nextval('public.hibernate_sequence'),'JENKINS_GA_COUNTY_PROPERTY',0.0099,null,null),
(nextval('public.hibernate_sequence'),'JOHNSON_GA_COUNTY_PROPERTY',0.0094,null,null),
(nextval('public.hibernate_sequence'),'JONES_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'LAMAR_GA_COUNTY_PROPERTY',0.0102,null,null),
(nextval('public.hibernate_sequence'),'LANIER_GA_COUNTY_PROPERTY',0.0111,null,null),
(nextval('public.hibernate_sequence'),'LAURENS_GA_COUNTY_PROPERTY',0.0078,null,null),
(nextval('public.hibernate_sequence'),'LEE_GA_COUNTY_PROPERTY',0.0098,null,null),
(nextval('public.hibernate_sequence'),'LIBERTY_GA_COUNTY_PROPERTY',0.0122,null,null),
(nextval('public.hibernate_sequence'),'LINCOLN_GA_COUNTY_PROPERTY',0.0092,null,null),
(nextval('public.hibernate_sequence'),'LONG_GA_COUNTY_PROPERTY',0.0122,null,null),
(nextval('public.hibernate_sequence'),'LOWNDES_GA_COUNTY_PROPERTY',0.0082,null,null),
(nextval('public.hibernate_sequence'),'LUMPKIN_GA_COUNTY_PROPERTY',0.0076,null,null),
(nextval('public.hibernate_sequence'),'MCDUFFIE_GA_COUNTY_PROPERTY',0.0089,null,null),
(nextval('public.hibernate_sequence'),'MCINTOSH_GA_COUNTY_PROPERTY',0.0097,null,null),
(nextval('public.hibernate_sequence'),'MACON_GA_COUNTY_PROPERTY',0.0096,null,null),
(nextval('public.hibernate_sequence'),'MADISON_GA_COUNTY_PROPERTY',0.0098,null,null),
(nextval('public.hibernate_sequence'),'MARION_GA_COUNTY_PROPERTY',0.0089,null,null),
(nextval('public.hibernate_sequence'),'MERIWETHER_GA_COUNTY_PROPERTY',0.0089,null,null),
(nextval('public.hibernate_sequence'),'MILLER_GA_COUNTY_PROPERTY',0.0110,null,null),
(nextval('public.hibernate_sequence'),'MITCHELL_GA_COUNTY_PROPERTY',0.0116,null,null),
(nextval('public.hibernate_sequence'),'MONROE_GA_COUNTY_PROPERTY',0.0072,null,null),
(nextval('public.hibernate_sequence'),'MONTGOMERY_GA_COUNTY_PROPERTY',0.0080,null,null),
(nextval('public.hibernate_sequence'),'MORGAN_GA_COUNTY_PROPERTY',0.0077,null,null),
(nextval('public.hibernate_sequence'),'MURRAY_GA_COUNTY_PROPERTY',0.0070,null,null),
(nextval('public.hibernate_sequence'),'MUSCOGEE_GA_COUNTY_PROPERTY',0.0070,null,null),
(nextval('public.hibernate_sequence'),'NEWTON_GA_COUNTY_PROPERTY',0.0110,null,null),
(nextval('public.hibernate_sequence'),'OCONEE_GA_COUNTY_PROPERTY',0.0087,null,null),
(nextval('public.hibernate_sequence'),'OGLETHORPE_GA_COUNTY_PROPERTY',0.0094,null,null),
(nextval('public.hibernate_sequence'),'PAULDING_GA_COUNTY_PROPERTY',0.0103,null,null),
(nextval('public.hibernate_sequence'),'PEACH_GA_COUNTY_PROPERTY',0.0110,null,null),
(nextval('public.hibernate_sequence'),'PICKENS_GA_COUNTY_PROPERTY',0.0080,null,null),
(nextval('public.hibernate_sequence'),'PIERCE_GA_COUNTY_PROPERTY',0.0098,null,null),
(nextval('public.hibernate_sequence'),'PIKE_GA_COUNTY_PROPERTY',0.0100,null,null),
(nextval('public.hibernate_sequence'),'POLK_GA_COUNTY_PROPERTY',0.0089,null,null),
(nextval('public.hibernate_sequence'),'PULASKI_GA_COUNTY_PROPERTY',0.0099,null,null),
(nextval('public.hibernate_sequence'),'PUTNAM_GA_COUNTY_PROPERTY',0.0058,null,null),
(nextval('public.hibernate_sequence'),'QUITMAN_GA_COUNTY_PROPERTY',0.0087,null,null),
(nextval('public.hibernate_sequence'),'RABUN_GA_COUNTY_PROPERTY',0.0059,null,null),
(nextval('public.hibernate_sequence'),'RANDOLPH_GA_COUNTY_PROPERTY',0.0086,null,null),
(nextval('public.hibernate_sequence'),'RICHMOND_GA_COUNTY_PROPERTY',0.0107,null,null),
(nextval('public.hibernate_sequence'),'ROCKDALE_GA_COUNTY_PROPERTY',0.0081,null,null),
(nextval('public.hibernate_sequence'),'SCHLEY_GA_COUNTY_PROPERTY',0.0106,null,null),
(nextval('public.hibernate_sequence'),'SCREVEN_GA_COUNTY_PROPERTY',0.0104,null,null),
(nextval('public.hibernate_sequence'),'SEMINOLE_GA_COUNTY_PROPERTY',0.0096,null,null),
(nextval('public.hibernate_sequence'),'SPALDING_GA_COUNTY_PROPERTY',0.0127,null,null),
(nextval('public.hibernate_sequence'),'STEPHENS_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'STEWART_GA_COUNTY_PROPERTY',0.0094,null,null),
(nextval('public.hibernate_sequence'),'SUMTER_GA_COUNTY_PROPERTY',0.0126,null,null),
(nextval('public.hibernate_sequence'),'TALBOT_GA_COUNTY_PROPERTY',0.0084,null,null),
(nextval('public.hibernate_sequence'),'TALIAFERRO_GA_COUNTY_PROPERTY',0.0136,null,null),
(nextval('public.hibernate_sequence'),'TATTNALL_GA_COUNTY_PROPERTY',0.0099,null,null),
(nextval('public.hibernate_sequence'),'TAYLOR_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'TELFAIR_GA_COUNTY_PROPERTY',0.0108,null,null),
(nextval('public.hibernate_sequence'),'TERRELL_GA_COUNTY_PROPERTY',0.0122,null,null),
(nextval('public.hibernate_sequence'),'THOMAS_GA_COUNTY_PROPERTY',0.0090,null,null),
(nextval('public.hibernate_sequence'),'TIFT_GA_COUNTY_PROPERTY',0.0095,null,null),
(nextval('public.hibernate_sequence'),'TOOMBS_GA_COUNTY_PROPERTY',0.0073,null,null),
(nextval('public.hibernate_sequence'),'TOWNS_GA_COUNTY_PROPERTY',0.0046,null,null),
(nextval('public.hibernate_sequence'),'TREUTLEN_GA_COUNTY_PROPERTY',0.0080,null,null),
(nextval('public.hibernate_sequence'),'TROUP_GA_COUNTY_PROPERTY',0.0100,null,null),
(nextval('public.hibernate_sequence'),'TURNER_GA_COUNTY_PROPERTY',0.0113,null,null),
(nextval('public.hibernate_sequence'),'TWIGGS_GA_COUNTY_PROPERTY',0.0102,null,null),
(nextval('public.hibernate_sequence'),'UNION_GA_COUNTY_PROPERTY',0.0055,null,null),
(nextval('public.hibernate_sequence'),'UPSON_GA_COUNTY_PROPERTY',0.0082,null,null),
(nextval('public.hibernate_sequence'),'WALKER_GA_COUNTY_PROPERTY',0.0073,null,null),
(nextval('public.hibernate_sequence'),'WALTON_GA_COUNTY_PROPERTY',0.0105,null,null),
(nextval('public.hibernate_sequence'),'WARE_GA_COUNTY_PROPERTY',0.0105,null,null),
(nextval('public.hibernate_sequence'),'WARREN_GA_COUNTY_PROPERTY',0.0079,null,null),
(nextval('public.hibernate_sequence'),'WASHINGTON_GA_COUNTY_PROPERTY',0.0090,null,null),
(nextval('public.hibernate_sequence'),'WAYNE_GA_COUNTY_PROPERTY',0.0088,null,null),
(nextval('public.hibernate_sequence'),'WEBSTER_GA_COUNTY_PROPERTY',0.0106,null,null),
(nextval('public.hibernate_sequence'),'WHEELER_GA_COUNTY_PROPERTY',0.0082,null,null),
(nextval('public.hibernate_sequence'),'WHITE_GA_COUNTY_PROPERTY',0.0079,null,null),
(nextval('public.hibernate_sequence'),'WHITFIELD_GA_COUNTY_PROPERTY',0.0068,null,null),
(nextval('public.hibernate_sequence'),'WILCOX_GA_COUNTY_PROPERTY',0.0082,null,null),
(nextval('public.hibernate_sequence'),'WILKES_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'WILKINSON_GA_COUNTY_PROPERTY',0.0093,null,null),
(nextval('public.hibernate_sequence'),'WORTH_GA_COUNTY_PROPERTY',0.0094,null,null)

;

INSERT INTO public.assessed_rate(
            id, tax_definition_key, rate)
    VALUES
(nextval('public.hibernate_sequence'),'APPLING_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'ATKINSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BACON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BAKER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BALDWIN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BANKS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BARROW_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BARTOW_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BEN_HILL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BERRIEN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BIBB_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BLECKLEY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BRANTLEY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BROOKS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BRYAN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BULLOCH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BURKE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'BUTTS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CALHOUN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CAMDEN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CANDLER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CARROLL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CATOOSA_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CHARLTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CHATHAM_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CHATTAHOOCHEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CHATTOOGA_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CHEROKEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CLARKE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CLAY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CLAYTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CLINCH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COBB_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COFFEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COLQUITT_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COLUMBIA_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COOK_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'COWETA_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CRAWFORD_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'CRISP_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DADE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DAWSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DECATUR_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DEKALB_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DODGE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DOOLY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DOUGHERTY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'DOUGLAS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'EARLY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'ECHOLS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'EFFINGHAM_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'ELBERT_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'EMANUEL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'EVANS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FANNIN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FAYETTE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FLOYD_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FORSYTH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FRANKLIN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'FULTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GILMER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GLASCOCK_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GLYNN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GORDON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GRADY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GREENE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'GWINNETT_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HABERSHAM_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HALL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HANCOCK_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HARALSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HARRIS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HART_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HEARD_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HENRY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'HOUSTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'IRWIN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JACKSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JASPER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JEFF_DAVIS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JEFFERSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JENKINS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JOHNSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'JONES_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LAMAR_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LANIER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LAURENS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LIBERTY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LINCOLN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LONG_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LOWNDES_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'LUMPKIN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MCDUFFIE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MCINTOSH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MACON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MADISON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MARION_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MERIWETHER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MILLER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MITCHELL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MONROE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MONTGOMERY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MORGAN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MURRAY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'MUSCOGEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'NEWTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'OCONEE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'OGLETHORPE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PAULDING_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PEACH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PICKENS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PIERCE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PIKE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'POLK_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PULASKI_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'PUTNAM_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'QUITMAN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'RABUN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'RANDOLPH_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'RICHMOND_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'ROCKDALE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'SCHLEY_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'SCREVEN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'SEMINOLE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'SPALDING_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'STEPHENS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'STEWART_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'SUMTER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TALBOT_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TALIAFERRO_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TATTNALL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TAYLOR_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TELFAIR_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TERRELL_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'THOMAS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TIFT_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TOOMBS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TOWNS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TREUTLEN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TROUP_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TURNER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'TWIGGS_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'UNION_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'UPSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WALKER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WALTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WARE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WARREN_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WASHINGTON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WAYNE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WEBSTER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WHEELER_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WHITE_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WHITFIELD_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WILCOX_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WILKES_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WILKINSON_GA_COUNTY_PROPERTY', 1.00),
(nextval('public.hibernate_sequence'),'WORTH_GA_COUNTY_PROPERTY', 1.00)

;
