-- Income Tax for cities in KY
-- tax_definition_income_city_KY.sql
INSERT INTO public.tax_definition(id, political_division_key, tax_definition_key, description, tax_calc_strategy, tax_type, ordinal)
VALUES
(nextval('public.hibernate_sequence'),'2100802','ALEXANDRIA_KY_CITY_INCOME','Alexandria city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2102368','ASHLAND_KY_CITY_INCOME','Ashland city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2103628','BARDSTOWN_KY_CITY_INCOME','Bardstown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105446','BELLEVUE_KY_CITY_INCOME','Bellevue city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105824','BENTON_KY_CITY_INCOME','Benton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105842','BEREA_KY_CITY_INCOME','Berea city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2108902','BOWLING_GREEN_KY_CITY_INCOME','Bowling Green city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2112160','CAMPBELLSVILLE_KY_CITY_INCOME','Campbellsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2116372','COLD_SPRING_KY_CITY_INCOME','Cold Spring city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2116750','COLUMBIA_KY_CITY_INCOME','Columbia city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2117848','COVINGTON_KY_CITY_INCOME','Covington city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2118352','CRESCENT_SPRINGS_KY_CITY_INCOME','Crescent Springs city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2119432','CYNTHIANA_KY_CITY_INCOME','Cynthiana city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2119882','DANVILLE_KY_CITY_INCOME','Danville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2120350','DAYTON_KY_CITY_INCOME','Dayton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2123932','EDGEWOOD_KY_CITY_INCOME','Edgewood city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2124274','ELIZABETHTOWN_KY_CITY_INCOME','Elizabethtown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2124778','ELSMERE_KY_CITY_INCOME','Elsmere city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2125300','ERLANGER_KY_CITY_INCOME','Erlanger city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2127982','FLORENCE_KY_CITY_INCOME','Florence city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128558','FORT_MITCHELL_KY_CITY_INCOME','Fort Mitchell city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128594','FORT_THOMAS_KY_CITY_INCOME','Fort Thomas city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128612','FORT_WRIGHT_KY_CITY_INCOME','Fort Wright city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128900','FRANKFORT_KY_CITY_INCOME','Frankfort city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128918','FRANKLIN_KY_CITY_INCOME','Franklin city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2130700','GEORGETOWN_KY_CITY_INCOME','Georgetown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2131114','GLASGOW_KY_CITY_INCOME','Glasgow city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2132572','GRAYSON_KY_CITY_INCOME','Grayson city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2134966','HARRODSBURG_KY_CITY_INCOME','Harrodsburg city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2135362','HAZARD_KY_CITY_INCOME','Hazard city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2135866','HENDERSON_KY_CITY_INCOME','Henderson city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2136604','HIGHLAND_HEIGHTS_KY_CITY_INCOME','Highland Heights city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2136982','HILLVIEW_KY_CITY_INCOME','Hillview city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2137396','HODGENVILLE_KY_CITY_INCOME','Hodgenville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2137918','HOPKINSVILLE_KY_CITY_INCOME','Hopkinsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2139142','INDEPENDENCE_KY_CITY_INCOME','Independence city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2140222','JEFFERSONTOWN_KY_CITY_INCOME','Jeffersontown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2143480','LA_GRANGE_KY_CITY_INCOME','La Grange city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2144344','LEBANON_KY_CITY_INCOME','Lebanon city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2144686','LEITCHFIELD_KY_CITY_INCOME','Leitchfield city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2146027','LEXINGTON_FAYETTE_URBAN_COUNTY_KY_CITY_INCOME','Lexington-Fayette urban county KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2148003','LOUISVILLE_JEFFERSON_COUNTY_METRO_GOVERNMENT_KY_CITY_INCOME','Louisville/Jefferson County metro government KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2148378','LUDLOW_KY_CITY_INCOME','Ludlow city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2149368','MADISONVILLE_KY_CITY_INCOME','Madisonville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2150898','MAYFIELD_KY_CITY_INCOME','Mayfield city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2151024','MAYSVILLE_KY_CITY_INCOME','Maysville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2151924','MIDDLESBOROUGH_KY_CITY_INCOME','Middlesborough city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2153418','MOREHEAD_KY_CITY_INCOME','Morehead city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2154228','MOUNT_WASHINGTON_KY_CITY_INCOME','Mount Washington city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2155884','NEWPORT_KY_CITY_INCOME','Newport city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2156136','NICHOLASVILLE_KY_CITY_INCOME','Nicholasville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2157090','OAK_GROVE_KY_CITY_INCOME','Oak Grove city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158620','OWENSBORO_KY_CITY_INCOME','Owensboro city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158836','PADUCAH_KY_CITY_INCOME','Paducah city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158962','PAINTSVILLE_KY_CITY_INCOME','Paintsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2159196','PARIS_KY_CITY_INCOME','Paris city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2160852','PIKEVILLE_KY_CITY_INCOME','Pikeville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2162940','PRESTONSBURG_KY_CITY_INCOME','Prestonsburg city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2163138','PRINCETON_KY_CITY_INCOME','Princeton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2163912','RADCLIFF_KY_CITY_INCOME','Radcliff city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2165226','RICHMOND_KY_CITY_INCOME','Richmond city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2167458','RUSSELL_KY_CITY_INCOME','Russell city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2167512','RUSSELLVILLE_KY_CITY_INCOME','Russellville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2169114','SCOTTSVILLE_KY_CITY_INCOME','Scottsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170050','SHELBYVILLE_KY_CITY_INCOME','Shelbyville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170086','SHEPHERDSVILLE_KY_CITY_INCOME','Shepherdsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170284','SHIVELY_KY_CITY_INCOME','Shively city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2171976','SOUTHGATE_KY_CITY_INCOME','Southgate city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2173110','STANFORD_KY_CITY_INCOME','Stanford city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2175738','TAYLOR_MILL_KY_CITY_INCOME','Taylor Mill city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179482','VERSAILLES_KY_CITY_INCOME','Versailles city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179698','VILLA_HILLS_KY_CITY_INCOME','Villa Hills city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179734','VINE_GROVE_KY_CITY_INCOME','Vine Grove city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2181858','WEST_LIBERTY_KY_CITY_INCOME','West Liberty city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2183550','WILMORE_KY_CITY_INCOME','Wilmore city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2183676','WINCHESTER_KY_CITY_INCOME','Winchester city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9)
;

-- tax_rate_income_city_KY.sql
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'),'ALEXANDRIA_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'ASHLAND_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'BARDSTOWN_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'BELLEVUE_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'BENTON_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'BEREA_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'BOWLING_GREEN_KY_CITY_INCOME',0.0185,null,null),
(nextval('public.hibernate_sequence'),'CAMPBELLSVILLE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COLD_SPRING_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COLUMBIA_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COVINGTON_KY_CITY_INCOME',0.0245,null,null),
(nextval('public.hibernate_sequence'),'CRESCENT_SPRINGS_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'CYNTHIANA_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'DANVILLE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'DAYTON_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'EDGEWOOD_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'ELIZABETHTOWN_KY_CITY_INCOME',0.0135,null,null),
(nextval('public.hibernate_sequence'),'ELSMERE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'ERLANGER_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'FLORENCE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'FORT_MITCHELL_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'FORT_THOMAS_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'FORT_WRIGHT_KY_CITY_INCOME',0.0115,null,null),
(nextval('public.hibernate_sequence'),'FRANKFORT_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GEORGETOWN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GLASGOW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'GRAYSON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HARRODSBURG_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HAZARD_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'HENDERSON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HIGHLAND_HEIGHTS_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HILLVIEW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'HODGENVILLE_KY_CITY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'HOPKINSVILLE_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'INDEPENDENCE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'JEFFERSONTOWN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LA_GRANGE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LEBANON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LEITCHFIELD_KY_CITY_INCOME',0.0120,null,null),
(nextval('public.hibernate_sequence'),'LEXINGTON_FAYETTE_URBAN_COUNTY_KY_CITY_INCOME',0.0225,null,null),
(nextval('public.hibernate_sequence'),'LOUISVILLE_JEFFERSON_COUNTY_METRO_GOVERNMENT_KY_CITY_INCOME',0.0220,null,null),
(nextval('public.hibernate_sequence'),'LUDLOW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MADISONVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MAYFIELD_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'MAYSVILLE_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'MIDDLESBOROUGH_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'MOREHEAD_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MOUNT_WASHINGTON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'NEWPORT_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'NICHOLASVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'OAK_GROVE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'OWENSBORO_KY_CITY_INCOME',0.0139,null,null),
(nextval('public.hibernate_sequence'),'PADUCAH_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'PAINTSVILLE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'PARIS_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'PIKEVILLE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'PRESTONSBURG_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'PRINCETON_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'RADCLIFF_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'RICHMOND_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'RUSSELL_KY_CITY_INCOME',0.0088,null,null),
(nextval('public.hibernate_sequence'),'RUSSELLVILLE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'SCOTTSVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHELBYVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHEPHERDSVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHIVELY_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SOUTHGATE_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'STANFORD_KY_CITY_INCOME',0.0065,null,null),
(nextval('public.hibernate_sequence'),'TAYLOR_MILL_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'VERSAILLES_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'VILLA_HILLS_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'VINE_GROVE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'WEST_LIBERTY_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'WILMORE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'WINCHESTER_KY_CITY_INCOME',0.0200,null,null)
;


