-- tax_definition city income
INSERT INTO public.tax_definition(id, tax_definition_key, description, tax_calc_strategy, tax_type, political_division_key, ordinal)
VALUES
(nextval('public.hibernate_sequence'), 'WILMINGTON_DE_CITY_INCOME', 'Wilmington DE City Wage Income', 'incomeTaxFlatRateCalculator', 'INCOME_CITY', '1077580', 4),
(nextval('public.hibernate_sequence'), 'NEW_YORK_NY_CITY_INCOME', 'New York NY City Income', 'incomeTaxBracketedMarginalRateCalculator', 'INCOME_CITY', '3651000', 4)
;

-- income_tax_definition
INSERT INTO public.income_tax_definition(id, tax_definition_key, deduct_itemized, deduct_pre_tax_contributions, standard_deduction_single, standard_deduction_joint, standard_deduction_married_filing_separate, standard_deduction_head_of_household, personal_exemption_single, personal_exemption_joint, personal_exemption_married_filing_separate, personal_exemption_head_of_household, dependent_exemption)
VALUES
(nextval('public.hibernate_sequence'), 'WILMINGTON_DE_CITY_INCOME', false, true, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(nextval('public.hibernate_sequence'), 'NEW_YORK_NY_CITY_INCOME', true, true, 8000, 16050, 8000, 11200, 0, 0, 0, 0, 1000)
;

-- tax_rate city income flat rate
INSERT INTO public.tax_rate(
            id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'), 'WILMINGTON_DE_CITY_INCOME', 0.0125, null, null)
;

-- tax_rate_set NY city income
INSERT INTO public.tax_rate_set(id, tax_definition_key, tax_filing_status)
VALUES
(36101, 'NEW_YORK_NY_CITY_INCOME', 'SINGLE'),
(36102, 'NEW_YORK_NY_CITY_INCOME', 'JOINT'),
(36103, 'NEW_YORK_NY_CITY_INCOME', 'MARRIED_SEPARATE'),
(36104, 'NEW_YORK_NY_CITY_INCOME', 'HEAD_OF_HOUSEHOLD')
;

-- tax_rate NY state income
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
-- Single, Married Separate
(36101, 'NEW_YORK_NY_CITY_INCOME', 0.03078, 0, 12000),
(36102, 'NEW_YORK_NY_CITY_INCOME', 0.03762, 12000, 25000),
(36103, 'NEW_YORK_NY_CITY_INCOME', 0.03819, 25000, 50000),
(36110, 'NEW_YORK_NY_CITY_INCOME', 0.03876, 50000, null),
-- Joint
(36111, 'NEW_YORK_NY_CITY_INCOME', 0.03078, 0, 21600),
(36112, 'NEW_YORK_NY_CITY_INCOME', 0.03762, 21600, 45000),
(36113, 'NEW_YORK_NY_CITY_INCOME', 0.03819, 45000, 90000),
(36120, 'NEW_YORK_NY_CITY_INCOME', 0.03876, 90000, null),
-- Head of Household
(36131, 'NEW_YORK_NY_CITY_INCOME', 0.03078, 0, 14400),
(36132, 'NEW_YORK_NY_CITY_INCOME', 0.03762, 14400, 30000),
(36133, 'NEW_YORK_NY_CITY_INCOME', 0.03819, 30000, 60000),
(36140, 'NEW_YORK_NY_CITY_INCOME', 0.03876, 60000, null)
;

-- tax_rate_set_tax_rates NY state income
INSERT INTO public.tax_rate_set_tax_rates(tax_rate_set_id, tax_rate_id)
VALUES
-- NY State Income - Single
(36101, 36101),
(36101, 36102),
(36101, 36103),
(36101, 36110),
-- NY State Income - Joint
(36102, 36111),
(36102, 36112),
(36102, 36113),
(36102, 36120),
-- NY State Income - Married Separate
(36103, 36101),
(36103, 36102),
(36103, 36103),
(36103, 36110),
-- NY State Income - Head of Household
(36104, 36131),
(36104, 36132),
(36104, 36133),
(36104, 36140)
;

-- Income Tax for counties in IN
-- tax_definition_income_IN.sql
INSERT INTO public.tax_definition(id, political_division_key, tax_definition_key, description, tax_calc_strategy, tax_type, ordinal)
VALUES
(nextval('public.hibernate_sequence'),'18001','ADAMS_IN_COUNTY_INCOME','Adams County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18003','ALLEN_IN_COUNTY_INCOME','Allen County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18005','BARTHOLOMEW_IN_COUNTY_INCOME','Bartholomew County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18007','BENTON_IN_COUNTY_INCOME','Benton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18009','BLACKFORD_IN_COUNTY_INCOME','Blackford County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18011','BOONE_IN_COUNTY_INCOME','Boone County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18013','BROWN_IN_COUNTY_INCOME','Brown County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18015','CARROLL_IN_COUNTY_INCOME','Carroll County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18017','CASS_IN_COUNTY_INCOME','Cass County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18019','CLARK_IN_COUNTY_INCOME','Clark County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18021','CLAY_IN_COUNTY_INCOME','Clay County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18023','CLINTON_IN_COUNTY_INCOME','Clinton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18025','CRAWFORD_IN_COUNTY_INCOME','Crawford County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18027','DAVIESS_IN_COUNTY_INCOME','Daviess County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18029','DEARBORN_IN_COUNTY_INCOME','Dearborn County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18031','DECATUR_IN_COUNTY_INCOME','Decatur County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18033','DEKALB_IN_COUNTY_INCOME','DeKalb County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18035','DELAWARE_IN_COUNTY_INCOME','Delaware County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18037','DUBOIS_IN_COUNTY_INCOME','Dubois County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18039','ELKHART_IN_COUNTY_INCOME','Elkhart County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18041','FAYETTE_IN_COUNTY_INCOME','Fayette County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18043','FLOYD_IN_COUNTY_INCOME','Floyd County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18045','FOUNTAIN_IN_COUNTY_INCOME','Fountain County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18047','FRANKLIN_IN_COUNTY_INCOME','Franklin County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18049','FULTON_IN_COUNTY_INCOME','Fulton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18051','GIBSON_IN_COUNTY_INCOME','Gibson County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18053','GRANT_IN_COUNTY_INCOME','Grant County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18055','GREENE_IN_COUNTY_INCOME','Greene County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18057','HAMILTON_IN_COUNTY_INCOME','Hamilton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18059','HANCOCK_IN_COUNTY_INCOME','Hancock County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18061','HARRISON_IN_COUNTY_INCOME','Harrison County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18063','HENDRICKS_IN_COUNTY_INCOME','Hendricks County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18065','HENRY_IN_COUNTY_INCOME','Henry County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18067','HOWARD_IN_COUNTY_INCOME','Howard County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18069','HUNTINGTON_IN_COUNTY_INCOME','Huntington County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18071','JACKSON_IN_COUNTY_INCOME','Jackson County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18073','JASPER_IN_COUNTY_INCOME','Jasper County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18075','JAY_IN_COUNTY_INCOME','Jay County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18077','JEFFERSON_IN_COUNTY_INCOME','Jefferson County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18079','JENNINGS_IN_COUNTY_INCOME','Jennings County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18081','JOHNSON_IN_COUNTY_INCOME','Johnson County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18083','KNOX_IN_COUNTY_INCOME','Knox County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18085','KOSCIUSKO_IN_COUNTY_INCOME','Kosciusko County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18087','LAGRANGE_IN_COUNTY_INCOME','LaGrange County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18089','LAKE_IN_COUNTY_INCOME','Lake County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18091','LAPORTE_IN_COUNTY_INCOME','LaPorte County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18093','LAWRENCE_IN_COUNTY_INCOME','Lawrence County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18095','MADISON_IN_COUNTY_INCOME','Madison County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18097','MARION_IN_COUNTY_INCOME','Marion County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18099','MARSHALL_IN_COUNTY_INCOME','Marshall County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18101','MARTIN_IN_COUNTY_INCOME','Martin County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18103','MIAMI_IN_COUNTY_INCOME','Miami County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18105','MONROE_IN_COUNTY_INCOME','Monroe County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18107','MONTGOMERY_IN_COUNTY_INCOME','Montgomery County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18109','MORGAN_IN_COUNTY_INCOME','Morgan County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18111','NEWTON_IN_COUNTY_INCOME','Newton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18113','NOBLE_IN_COUNTY_INCOME','Noble County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18115','OHIO_IN_COUNTY_INCOME','Ohio County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18117','ORANGE_IN_COUNTY_INCOME','Orange County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18119','OWEN_IN_COUNTY_INCOME','Owen County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18121','PARKE_IN_COUNTY_INCOME','Parke County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18123','PERRY_IN_COUNTY_INCOME','Perry County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18125','PIKE_IN_COUNTY_INCOME','Pike County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18127','PORTER_IN_COUNTY_INCOME','Porter County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18129','POSEY_IN_COUNTY_INCOME','Posey County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18131','PULASKI_IN_COUNTY_INCOME','Pulaski County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18133','PUTNAM_IN_COUNTY_INCOME','Putnam County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18135','RANDOLPH_IN_COUNTY_INCOME','Randolph County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18137','RIPLEY_IN_COUNTY_INCOME','Ripley County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18139','RUSH_IN_COUNTY_INCOME','Rush County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18143','SCOTT_IN_COUNTY_INCOME','Scott County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18145','SHELBY_IN_COUNTY_INCOME','Shelby County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18147','SPENCER_IN_COUNTY_INCOME','Spencer County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18141','ST_JOSEPH_IN_COUNTY_INCOME','St. Joseph County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18149','STARKE_IN_COUNTY_INCOME','Starke County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18151','STEUBEN_IN_COUNTY_INCOME','Steuben County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18153','SULLIVAN_IN_COUNTY_INCOME','Sullivan County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18155','SWITZERLAND_IN_COUNTY_INCOME','Switzerland County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18157','TIPPECANOE_IN_COUNTY_INCOME','Tippecanoe County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18159','TIPTON_IN_COUNTY_INCOME','Tipton County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18161','UNION_IN_COUNTY_INCOME','Union County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18163','VANDERBURGH_IN_COUNTY_INCOME','Vanderburgh County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18165','VERMILLION_IN_COUNTY_INCOME','Vermillion County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18167','VIGO_IN_COUNTY_INCOME','Vigo County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18169','WABASH_IN_COUNTY_INCOME','Wabash County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18171','WARREN_IN_COUNTY_INCOME','Warren County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18173','WARRICK_IN_COUNTY_INCOME','Warrick County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18175','WASHINGTON_IN_COUNTY_INCOME','Washington County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18177','WAYNE_IN_COUNTY_INCOME','Wayne County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18179','WELLS_IN_COUNTY_INCOME','Wells County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18181','WHITE_IN_COUNTY_INCOME','White County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'18183','WHITLEY_IN_COUNTY_INCOME','Whitley County IN Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9)
;

-- tax_rate_income_IN.sql
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'),'ADAMS_IN_COUNTY_INCOME',0.01624,null,null),
(nextval('public.hibernate_sequence'),'ALLEN_IN_COUNTY_INCOME',0.01480,null,null),
(nextval('public.hibernate_sequence'),'BARTHOLOMEW_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'BENTON_IN_COUNTY_INCOME',0.01790,null,null),
(nextval('public.hibernate_sequence'),'BLACKFORD_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'BOONE_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'BROWN_IN_COUNTY_INCOME',0.02523,null,null),
(nextval('public.hibernate_sequence'),'CARROLL_IN_COUNTY_INCOME',0.02073,null,null),
(nextval('public.hibernate_sequence'),'CASS_IN_COUNTY_INCOME',0.02500,null,null),
(nextval('public.hibernate_sequence'),'CLARK_IN_COUNTY_INCOME',0.02000,null,null),
(nextval('public.hibernate_sequence'),'CLAY_IN_COUNTY_INCOME',0.02250,null,null),
(nextval('public.hibernate_sequence'),'CLINTON_IN_COUNTY_INCOME',0.02250,null,null),
(nextval('public.hibernate_sequence'),'CRAWFORD_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'DAVIESS_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'DEARBORN_IN_COUNTY_INCOME',0.00600,null,null),
(nextval('public.hibernate_sequence'),'DECATUR_IN_COUNTY_INCOME',0.02350,null,null),
(nextval('public.hibernate_sequence'),'DEKALB_IN_COUNTY_INCOME',0.02130,null,null),
(nextval('public.hibernate_sequence'),'DELAWARE_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'DUBOIS_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'ELKHART_IN_COUNTY_INCOME',0.02000,null,null),
(nextval('public.hibernate_sequence'),'FAYETTE_IN_COUNTY_INCOME',0.02370,null,null),
(nextval('public.hibernate_sequence'),'FLOYD_IN_COUNTY_INCOME',0.01350,null,null),
(nextval('public.hibernate_sequence'),'FOUNTAIN_IN_COUNTY_INCOME',0.02100,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'FULTON_IN_COUNTY_INCOME',0.02380,null,null),
(nextval('public.hibernate_sequence'),'GIBSON_IN_COUNTY_INCOME',0.00700,null,null),
(nextval('public.hibernate_sequence'),'GRANT_IN_COUNTY_INCOME',0.02250,null,null),
(nextval('public.hibernate_sequence'),'GREENE_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'HAMILTON_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'HANCOCK_IN_COUNTY_INCOME',0.01700,null,null),
(nextval('public.hibernate_sequence'),'HARRISON_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'HENDRICKS_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'HENRY_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'HOWARD_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'HUNTINGTON_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'JACKSON_IN_COUNTY_INCOME',0.02100,null,null),
(nextval('public.hibernate_sequence'),'JASPER_IN_COUNTY_INCOME',0.02864,null,null),
(nextval('public.hibernate_sequence'),'JAY_IN_COUNTY_INCOME',0.02450,null,null),
(nextval('public.hibernate_sequence'),'JEFFERSON_IN_COUNTY_INCOME',0.00350,null,null),
(nextval('public.hibernate_sequence'),'JENNINGS_IN_COUNTY_INCOME',0.02500,null,null),
(nextval('public.hibernate_sequence'),'JOHNSON_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'KNOX_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'KOSCIUSKO_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'LAGRANGE_IN_COUNTY_INCOME',0.01650,null,null),
(nextval('public.hibernate_sequence'),'LAKE_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'LAPORTE_IN_COUNTY_INCOME',0.00950,null,null),
(nextval('public.hibernate_sequence'),'LAWRENCE_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'MADISON_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'MARION_IN_COUNTY_INCOME',0.02020,null,null),
(nextval('public.hibernate_sequence'),'MARSHALL_IN_COUNTY_INCOME',0.01250,null,null),
(nextval('public.hibernate_sequence'),'MARTIN_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'MIAMI_IN_COUNTY_INCOME',0.02540,null,null),
(nextval('public.hibernate_sequence'),'MONROE_IN_COUNTY_INCOME',0.01345,null,null),
(nextval('public.hibernate_sequence'),'MONTGOMERY_IN_COUNTY_INCOME',0.02300,null,null),
(nextval('public.hibernate_sequence'),'MORGAN_IN_COUNTY_INCOME',0.02720,null,null),
(nextval('public.hibernate_sequence'),'NEWTON_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'NOBLE_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'OHIO_IN_COUNTY_INCOME',0.01250,null,null),
(nextval('public.hibernate_sequence'),'ORANGE_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'OWEN_IN_COUNTY_INCOME',0.01300,null,null),
(nextval('public.hibernate_sequence'),'PARKE_IN_COUNTY_INCOME',0.02650,null,null),
(nextval('public.hibernate_sequence'),'PERRY_IN_COUNTY_INCOME',0.01810,null,null),
(nextval('public.hibernate_sequence'),'PIKE_IN_COUNTY_INCOME',0.00750,null,null),
(nextval('public.hibernate_sequence'),'PORTER_IN_COUNTY_INCOME',0.00500,null,null),
(nextval('public.hibernate_sequence'),'POSEY_IN_COUNTY_INCOME',0.01250,null,null),
(nextval('public.hibernate_sequence'),'PULASKI_IN_COUNTY_INCOME',0.03380,null,null),
(nextval('public.hibernate_sequence'),'PUTNAM_IN_COUNTY_INCOME',0.02000,null,null),
(nextval('public.hibernate_sequence'),'RANDOLPH_IN_COUNTY_INCOME',0.02250,null,null),
(nextval('public.hibernate_sequence'),'RIPLEY_IN_COUNTY_INCOME',0.01380,null,null),
(nextval('public.hibernate_sequence'),'RUSH_IN_COUNTY_INCOME',0.02100,null,null),
(nextval('public.hibernate_sequence'),'SCOTT_IN_COUNTY_INCOME',0.02160,null,null),
(nextval('public.hibernate_sequence'),'SHELBY_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'SPENCER_IN_COUNTY_INCOME',0.00800,null,null),
(nextval('public.hibernate_sequence'),'ST_JOSEPH_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'STARKE_IN_COUNTY_INCOME',0.01710,null,null),
(nextval('public.hibernate_sequence'),'STEUBEN_IN_COUNTY_INCOME',0.01790,null,null),
(nextval('public.hibernate_sequence'),'SULLIVAN_IN_COUNTY_INCOME',0.00600,null,null),
(nextval('public.hibernate_sequence'),'SWITZERLAND_IN_COUNTY_INCOME',0.01000,null,null),
(nextval('public.hibernate_sequence'),'TIPPECANOE_IN_COUNTY_INCOME',0.01100,null,null),
(nextval('public.hibernate_sequence'),'TIPTON_IN_COUNTY_INCOME',0.02600,null,null),
(nextval('public.hibernate_sequence'),'UNION_IN_COUNTY_INCOME',0.01750,null,null),
(nextval('public.hibernate_sequence'),'VANDERBURGH_IN_COUNTY_INCOME',0.01200,null,null),
(nextval('public.hibernate_sequence'),'VERMILLION_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'VIGO_IN_COUNTY_INCOME',0.02000,null,null),
(nextval('public.hibernate_sequence'),'WABASH_IN_COUNTY_INCOME',0.02900,null,null),
(nextval('public.hibernate_sequence'),'WARREN_IN_COUNTY_INCOME',0.02120,null,null),
(nextval('public.hibernate_sequence'),'WARRICK_IN_COUNTY_INCOME',0.00500,null,null),
(nextval('public.hibernate_sequence'),'WASHINGTON_IN_COUNTY_INCOME',0.02000,null,null),
(nextval('public.hibernate_sequence'),'WAYNE_IN_COUNTY_INCOME',0.01500,null,null),
(nextval('public.hibernate_sequence'),'WELLS_IN_COUNTY_INCOME',0.02100,null,null),
(nextval('public.hibernate_sequence'),'WHITE_IN_COUNTY_INCOME',0.01320,null,null),
(nextval('public.hibernate_sequence'),'WHITLEY_IN_COUNTY_INCOME',0.01483,null,null)
;

-- Income Tax for counties in KY
-- tax_definition_income_KY.sql
INSERT INTO public.tax_definition(id, political_division_key, tax_definition_key, description, tax_calc_strategy, tax_type, ordinal)
VALUES
(nextval('public.hibernate_sequence'),'21015','BOONE_KY_COUNTY_INCOME','Boone County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21017','BOURBON_KY_COUNTY_INCOME','Bourbon County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21019','BOYD_KY_COUNTY_INCOME','Boyd County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21021','BOYLE_KY_COUNTY_INCOME','Boyle County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21037','CAMPBELL_KY_COUNTY_INCOME','Campbell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21041','CARROLL_KY_COUNTY_INCOME','Carroll County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21053','CLINTON_KY_COUNTY_INCOME','Clinton County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21057','CUMBERLAND_KY_COUNTY_INCOME','Cumberland County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21059','DAVIESS_KY_COUNTY_INCOME','Daviess County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21067','FAYETTE_KY_COUNTY_INCOME','Fayette County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21073','FRANKLIN_KY_COUNTY_INCOME','Franklin County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21079','GARRARD_KY_COUNTY_INCOME','Garrard County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21091','HANCOCK_KY_COUNTY_INCOME','Hancock County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21097','HARRISON_KY_COUNTY_INCOME','Harrison County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21099','HART_KY_COUNTY_INCOME','Hart County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21101','HENDERSON_KY_COUNTY_INCOME','Henderson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21113','JESSAMINE_KY_COUNTY_INCOME','Jessamine County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21115','JOHNSON_KY_COUNTY_INCOME','Johnson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21117','KENTON_KY_COUNTY_INCOME','Kenton County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21121','KNOX_KY_COUNTY_INCOME','Knox County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21125','LAUREL_KY_COUNTY_INCOME','Laurel County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21137','LINCOLN_KY_COUNTY_INCOME','Lincoln County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21139','LIVINGSTON_KY_COUNTY_INCOME','Livingston County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21141','LOGAN_KY_COUNTY_INCOME','Logan County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21151','MADISON_KY_COUNTY_INCOME','Madison County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21155','MARION_KY_COUNTY_INCOME','Marion County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21157','MARSHALL_KY_COUNTY_INCOME','Marshall County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21159','MARTIN_KY_COUNTY_INCOME','Martin County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21147','MCCREARY_KY_COUNTY_INCOME','McCreary County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21167','MERCER_KY_COUNTY_INCOME','Mercer County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21173','MONTGOMERY_KY_COUNTY_INCOME','Montgomery County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21179','NELSON_KY_COUNTY_INCOME','Nelson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21183','OHIO_KY_COUNTY_INCOME','Ohio County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21195','PIKE_KY_COUNTY_INCOME','Pike County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21197','POWELL_KY_COUNTY_INCOME','Powell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21203','ROCKCASTLE_KY_COUNTY_INCOME','Rockcastle County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21205','ROWAN_KY_COUNTY_INCOME','Rowan County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21207','RUSSELL_KY_COUNTY_INCOME','Russell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21209','SCOTT_KY_COUNTY_INCOME','Scott County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21211','SHELBY_KY_COUNTY_INCOME','Shelby County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21217','TAYLOR_KY_COUNTY_INCOME','Taylor County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21225','UNION_KY_COUNTY_INCOME','Union County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21227','WARREN_KY_COUNTY_INCOME','Warren County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21229','WASHINGTON_KY_COUNTY_INCOME','Washington County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21235','WHITLEY_KY_COUNTY_INCOME','Whitley County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9)
;

-- tax_rate_income_KY.sql
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'),'BOONE_KY_COUNTY_INCOME',0.0145,null,null),
(nextval('public.hibernate_sequence'),'BOURBON_KY_COUNTY_INCOME',0.0001,null,null),
(nextval('public.hibernate_sequence'),'BOYD_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'BOYLE_KY_COUNTY_INCOME',0.0001,null,null),
(nextval('public.hibernate_sequence'),'CAMPBELL_KY_COUNTY_INCOME',0.0105,null,null),
(nextval('public.hibernate_sequence'),'CARROLL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'CLINTON_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'CUMBERLAND_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'DAVIESS_KY_COUNTY_INCOME',0.0035,null,null),
(nextval('public.hibernate_sequence'),'FAYETTE_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GARRARD_KY_COUNTY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'HANCOCK_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'HARRISON_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'HART_KY_COUNTY_INCOME',0.0080,null,null),
(nextval('public.hibernate_sequence'),'HENDERSON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'JESSAMINE_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'JOHNSON_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'KENTON_KY_COUNTY_INCOME',0.0071,null,null),
(nextval('public.hibernate_sequence'),'KNOX_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LAUREL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LINCOLN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LIVINGSTON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LOGAN_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'MADISON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARION_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARSHALL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARTIN_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MCCREARY_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MERCER_KY_COUNTY_INCOME',0.0045,null,null),
(nextval('public.hibernate_sequence'),'MONTGOMERY_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'NELSON_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'OHIO_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'PIKE_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'POWELL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'ROCKCASTLE_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'ROWAN_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'RUSSELL_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'SCOTT_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'SHELBY_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'TAYLOR_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'UNION_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'WARREN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'WASHINGTON_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'WHITLEY_KY_COUNTY_INCOME',0.0100,null,null)
;

-- Income Tax for cities in KY
-- tax_definition_income_city_KY.sql
INSERT INTO public.tax_definition(id, political_division_key, tax_definition_key, description, tax_calc_strategy, tax_type, ordinal)
VALUES
(nextval('public.hibernate_sequence'),'2100802','ALEXANDRIA_KY_CITY_INCOME','Alexandria city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2102368','ASHLAND_KY_CITY_INCOME','Ashland city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2103628','BARDSTOWN_KY_CITY_INCOME','Bardstown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105446','BELLEVUE_KY_CITY_INCOME','Bellevue city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105824','BENTON_KY_CITY_INCOME','Benton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2105842','BEREA_KY_CITY_INCOME','Berea city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2108902','BOWLING_GREEN_KY_CITY_INCOME','Bowling Green city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2112160','CAMPBELLSVILLE_KY_CITY_INCOME','Campbellsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2116372','COLD_SPRING_KY_CITY_INCOME','Cold Spring city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2116750','COLUMBIA_KY_CITY_INCOME','Columbia city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2117848','COVINGTON_KY_CITY_INCOME','Covington city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2118352','CRESCENT_SPRINGS_KY_CITY_INCOME','Crescent Springs city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2119432','CYNTHIANA_KY_CITY_INCOME','Cynthiana city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2119882','DANVILLE_KY_CITY_INCOME','Danville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2120350','DAYTON_KY_CITY_INCOME','Dayton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2123932','EDGEWOOD_KY_CITY_INCOME','Edgewood city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2124274','ELIZABETHTOWN_KY_CITY_INCOME','Elizabethtown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2124778','ELSMERE_KY_CITY_INCOME','Elsmere city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2125300','ERLANGER_KY_CITY_INCOME','Erlanger city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2127982','FLORENCE_KY_CITY_INCOME','Florence city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128558','FORT_MITCHELL_KY_CITY_INCOME','Fort Mitchell city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128594','FORT_THOMAS_KY_CITY_INCOME','Fort Thomas city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128612','FORT_WRIGHT_KY_CITY_INCOME','Fort Wright city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128900','FRANKFORT_KY_CITY_INCOME','Frankfort city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2128918','FRANKLIN_KY_CITY_INCOME','Franklin city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2130700','GEORGETOWN_KY_CITY_INCOME','Georgetown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2131114','GLASGOW_KY_CITY_INCOME','Glasgow city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2132572','GRAYSON_KY_CITY_INCOME','Grayson city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2134966','HARRODSBURG_KY_CITY_INCOME','Harrodsburg city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2135362','HAZARD_KY_CITY_INCOME','Hazard city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2135866','HENDERSON_KY_CITY_INCOME','Henderson city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2136604','HIGHLAND_HEIGHTS_KY_CITY_INCOME','Highland Heights city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2136982','HILLVIEW_KY_CITY_INCOME','Hillview city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2137396','HODGENVILLE_KY_CITY_INCOME','Hodgenville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2137918','HOPKINSVILLE_KY_CITY_INCOME','Hopkinsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2139142','INDEPENDENCE_KY_CITY_INCOME','Independence city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2140222','JEFFERSONTOWN_KY_CITY_INCOME','Jeffersontown city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2143480','LA_GRANGE_KY_CITY_INCOME','La Grange city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2144344','LEBANON_KY_CITY_INCOME','Lebanon city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2144686','LEITCHFIELD_KY_CITY_INCOME','Leitchfield city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2146027','LEXINGTON_FAYETTE_URBAN_COUNTY_KY_CITY_INCOME','Lexington-Fayette urban county KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2148003','LOUISVILLE_JEFFERSON_COUNTY_METRO_GOVERNMENT_KY_CITY_INCOME','Louisville/Jefferson County metro government KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2148378','LUDLOW_KY_CITY_INCOME','Ludlow city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2149368','MADISONVILLE_KY_CITY_INCOME','Madisonville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2150898','MAYFIELD_KY_CITY_INCOME','Mayfield city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2151024','MAYSVILLE_KY_CITY_INCOME','Maysville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2151924','MIDDLESBOROUGH_KY_CITY_INCOME','Middlesborough city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2153418','MOREHEAD_KY_CITY_INCOME','Morehead city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2154228','MOUNT_WASHINGTON_KY_CITY_INCOME','Mount Washington city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2155884','NEWPORT_KY_CITY_INCOME','Newport city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2156136','NICHOLASVILLE_KY_CITY_INCOME','Nicholasville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2157090','OAK_GROVE_KY_CITY_INCOME','Oak Grove city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158620','OWENSBORO_KY_CITY_INCOME','Owensboro city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158836','PADUCAH_KY_CITY_INCOME','Paducah city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2158962','PAINTSVILLE_KY_CITY_INCOME','Paintsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2159196','PARIS_KY_CITY_INCOME','Paris city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2160852','PIKEVILLE_KY_CITY_INCOME','Pikeville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2162940','PRESTONSBURG_KY_CITY_INCOME','Prestonsburg city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2163138','PRINCETON_KY_CITY_INCOME','Princeton city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2163912','RADCLIFF_KY_CITY_INCOME','Radcliff city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2165226','RICHMOND_KY_CITY_INCOME','Richmond city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2167458','RUSSELL_KY_CITY_INCOME','Russell city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2167512','RUSSELLVILLE_KY_CITY_INCOME','Russellville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2169114','SCOTTSVILLE_KY_CITY_INCOME','Scottsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170050','SHELBYVILLE_KY_CITY_INCOME','Shelbyville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170086','SHEPHERDSVILLE_KY_CITY_INCOME','Shepherdsville city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2170284','SHIVELY_KY_CITY_INCOME','Shively city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2171976','SOUTHGATE_KY_CITY_INCOME','Southgate city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2173110','STANFORD_KY_CITY_INCOME','Stanford city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2175738','TAYLOR_MILL_KY_CITY_INCOME','Taylor Mill city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179482','VERSAILLES_KY_CITY_INCOME','Versailles city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179698','VILLA_HILLS_KY_CITY_INCOME','Villa Hills city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2179734','VINE_GROVE_KY_CITY_INCOME','Vine Grove city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2181858','WEST_LIBERTY_KY_CITY_INCOME','West Liberty city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2183550','WILMORE_KY_CITY_INCOME','Wilmore city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9),
(nextval('public.hibernate_sequence'),'2183676','WINCHESTER_KY_CITY_INCOME','Winchester city KY Income','incomeTaxFlatRateCalculator','INCOME_CITY',9)
;

-- tax_rate_income_city_KY.sql
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'),'ALEXANDRIA_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'ASHLAND_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'BARDSTOWN_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'BELLEVUE_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'BENTON_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'BEREA_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'BOWLING_GREEN_KY_CITY_INCOME',0.0185,null,null),
(nextval('public.hibernate_sequence'),'CAMPBELLSVILLE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COLD_SPRING_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COLUMBIA_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'COVINGTON_KY_CITY_INCOME',0.0245,null,null),
(nextval('public.hibernate_sequence'),'CRESCENT_SPRINGS_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'CYNTHIANA_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'DANVILLE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'DAYTON_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'EDGEWOOD_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'ELIZABETHTOWN_KY_CITY_INCOME',0.0135,null,null),
(nextval('public.hibernate_sequence'),'ELSMERE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'ERLANGER_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'FLORENCE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'FORT_MITCHELL_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'FORT_THOMAS_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'FORT_WRIGHT_KY_CITY_INCOME',0.0115,null,null),
(nextval('public.hibernate_sequence'),'FRANKFORT_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GEORGETOWN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GLASGOW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'GRAYSON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HARRODSBURG_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HAZARD_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'HENDERSON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HIGHLAND_HEIGHTS_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'HILLVIEW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'HODGENVILLE_KY_CITY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'HOPKINSVILLE_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'INDEPENDENCE_KY_CITY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'JEFFERSONTOWN_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LA_GRANGE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LEBANON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LEITCHFIELD_KY_CITY_INCOME',0.0120,null,null),
(nextval('public.hibernate_sequence'),'LEXINGTON_FAYETTE_URBAN_COUNTY_KY_CITY_INCOME',0.0225,null,null),
(nextval('public.hibernate_sequence'),'LOUISVILLE_JEFFERSON_COUNTY_METRO_GOVERNMENT_KY_CITY_INCOME',0.0220,null,null),
(nextval('public.hibernate_sequence'),'LUDLOW_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MADISONVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MAYFIELD_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'MAYSVILLE_KY_CITY_INCOME',0.0195,null,null),
(nextval('public.hibernate_sequence'),'MIDDLESBOROUGH_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'MOREHEAD_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MOUNT_WASHINGTON_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'NEWPORT_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'NICHOLASVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'OAK_GROVE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'OWENSBORO_KY_CITY_INCOME',0.0139,null,null),
(nextval('public.hibernate_sequence'),'PADUCAH_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'PAINTSVILLE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'PARIS_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'PIKEVILLE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'PRESTONSBURG_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'PRINCETON_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'RADCLIFF_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'RICHMOND_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'RUSSELL_KY_CITY_INCOME',0.0088,null,null),
(nextval('public.hibernate_sequence'),'RUSSELLVILLE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'SCOTTSVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHELBYVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHEPHERDSVILLE_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SHIVELY_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'SOUTHGATE_KY_CITY_INCOME',0.0250,null,null),
(nextval('public.hibernate_sequence'),'STANFORD_KY_CITY_INCOME',0.0065,null,null),
(nextval('public.hibernate_sequence'),'TAYLOR_MILL_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'VERSAILLES_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'VILLA_HILLS_KY_CITY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'VINE_GROVE_KY_CITY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'WEST_LIBERTY_KY_CITY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'WILMORE_KY_CITY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'WINCHESTER_KY_CITY_INCOME',0.0200,null,null)
;

