-- Income Tax for counties in KY
-- tax_definition_income_KY.sql
INSERT INTO public.tax_definition(id, political_division_key, tax_definition_key, description, tax_calc_strategy, tax_type, ordinal)
VALUES
(nextval('public.hibernate_sequence'),'21015','BOONE_KY_COUNTY_INCOME','Boone County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21017','BOURBON_KY_COUNTY_INCOME','Bourbon County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21019','BOYD_KY_COUNTY_INCOME','Boyd County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21021','BOYLE_KY_COUNTY_INCOME','Boyle County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21037','CAMPBELL_KY_COUNTY_INCOME','Campbell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21041','CARROLL_KY_COUNTY_INCOME','Carroll County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21053','CLINTON_KY_COUNTY_INCOME','Clinton County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21057','CUMBERLAND_KY_COUNTY_INCOME','Cumberland County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21059','DAVIESS_KY_COUNTY_INCOME','Daviess County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21067','FAYETTE_KY_COUNTY_INCOME','Fayette County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21073','FRANKLIN_KY_COUNTY_INCOME','Franklin County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21079','GARRARD_KY_COUNTY_INCOME','Garrard County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21091','HANCOCK_KY_COUNTY_INCOME','Hancock County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21097','HARRISON_KY_COUNTY_INCOME','Harrison County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21099','HART_KY_COUNTY_INCOME','Hart County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21101','HENDERSON_KY_COUNTY_INCOME','Henderson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21113','JESSAMINE_KY_COUNTY_INCOME','Jessamine County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21115','JOHNSON_KY_COUNTY_INCOME','Johnson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21117','KENTON_KY_COUNTY_INCOME','Kenton County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21121','KNOX_KY_COUNTY_INCOME','Knox County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21125','LAUREL_KY_COUNTY_INCOME','Laurel County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21137','LINCOLN_KY_COUNTY_INCOME','Lincoln County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21139','LIVINGSTON_KY_COUNTY_INCOME','Livingston County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21141','LOGAN_KY_COUNTY_INCOME','Logan County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21151','MADISON_KY_COUNTY_INCOME','Madison County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21155','MARION_KY_COUNTY_INCOME','Marion County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21157','MARSHALL_KY_COUNTY_INCOME','Marshall County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21159','MARTIN_KY_COUNTY_INCOME','Martin County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21147','MCCREARY_KY_COUNTY_INCOME','McCreary County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21167','MERCER_KY_COUNTY_INCOME','Mercer County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21173','MONTGOMERY_KY_COUNTY_INCOME','Montgomery County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21179','NELSON_KY_COUNTY_INCOME','Nelson County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21183','OHIO_KY_COUNTY_INCOME','Ohio County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21195','PIKE_KY_COUNTY_INCOME','Pike County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21197','POWELL_KY_COUNTY_INCOME','Powell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21203','ROCKCASTLE_KY_COUNTY_INCOME','Rockcastle County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21205','ROWAN_KY_COUNTY_INCOME','Rowan County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21207','RUSSELL_KY_COUNTY_INCOME','Russell County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21209','SCOTT_KY_COUNTY_INCOME','Scott County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21211','SHELBY_KY_COUNTY_INCOME','Shelby County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21217','TAYLOR_KY_COUNTY_INCOME','Taylor County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21225','UNION_KY_COUNTY_INCOME','Union County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21227','WARREN_KY_COUNTY_INCOME','Warren County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21229','WASHINGTON_KY_COUNTY_INCOME','Washington County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9),
(nextval('public.hibernate_sequence'),'21235','WHITLEY_KY_COUNTY_INCOME','Whitley County KY Income','incomeTaxFlatRateCalculator','INCOME_COUNTY',9)
;

-- tax_rate_income_KY.sql
INSERT INTO public.tax_rate(id, tax_definition_key, rate, range_low, range_high)
VALUES
(nextval('public.hibernate_sequence'),'BOONE_KY_COUNTY_INCOME',0.0145,null,null),
(nextval('public.hibernate_sequence'),'BOURBON_KY_COUNTY_INCOME',0.0001,null,null),
(nextval('public.hibernate_sequence'),'BOYD_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'BOYLE_KY_COUNTY_INCOME',0.0001,null,null),
(nextval('public.hibernate_sequence'),'CAMPBELL_KY_COUNTY_INCOME',0.0105,null,null),
(nextval('public.hibernate_sequence'),'CARROLL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'CLINTON_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'CUMBERLAND_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'DAVIESS_KY_COUNTY_INCOME',0.0035,null,null),
(nextval('public.hibernate_sequence'),'FAYETTE_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'FRANKLIN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'GARRARD_KY_COUNTY_INCOME',0.0200,null,null),
(nextval('public.hibernate_sequence'),'HANCOCK_KY_COUNTY_INCOME',0.0125,null,null),
(nextval('public.hibernate_sequence'),'HARRISON_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'HART_KY_COUNTY_INCOME',0.0080,null,null),
(nextval('public.hibernate_sequence'),'HENDERSON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'JESSAMINE_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'JOHNSON_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'KENTON_KY_COUNTY_INCOME',0.0071,null,null),
(nextval('public.hibernate_sequence'),'KNOX_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LAUREL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LINCOLN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LIVINGSTON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'LOGAN_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'MADISON_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARION_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARSHALL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'MARTIN_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MCCREARY_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'MERCER_KY_COUNTY_INCOME',0.0045,null,null),
(nextval('public.hibernate_sequence'),'MONTGOMERY_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'NELSON_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'OHIO_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'PIKE_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'POWELL_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'ROCKCASTLE_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'ROWAN_KY_COUNTY_INCOME',0.0150,null,null),
(nextval('public.hibernate_sequence'),'RUSSELL_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'SCOTT_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'SHELBY_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'TAYLOR_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'UNION_KY_COUNTY_INCOME',0.0050,null,null),
(nextval('public.hibernate_sequence'),'WARREN_KY_COUNTY_INCOME',0.0100,null,null),
(nextval('public.hibernate_sequence'),'WASHINGTON_KY_COUNTY_INCOME',0.0075,null,null),
(nextval('public.hibernate_sequence'),'WHITLEY_KY_COUNTY_INCOME',0.0100,null,null)
;


